### ISSUE TITLE
Data URLs not accepted as valid

### ISSUE THREAD

**Issue by Fyren** [cadeyrn/newtaboverride#1]
Using 7.0.0, the extension won't accept a data URL as valid input.  For example `data:text/html,<html style="background: black"></html>` works as expected if I put it in the browser address bar.

**Comment by cadeyrn** [comment]
Thank you for the report!

WebExtensions does not allow the opening of tabs with data URIs, only with valid HTTP(S) URIs. If you only want to set an empty page with a background color, I think I could implement such a feature (set a background color) in the next feature update.

Would this be good enough or is there another use case why do you need data URIs?

**Comment by cadeyrn** [comment]
I opened #9 to implement this feature. Thank you for reporting.

**Comment by cadeyrn** [comment]
> If you only want to set an empty page with a background color, I think I could implement such a feature (set a background color) in the next feature update.

Shipped with New Tab Override 8.0.
