### ISSUE TITLE
Please allow focus to be set to web page instead of URL, again...

### ISSUE THREAD

**Issue by grauenwolfe** [cadeyrn/newtaboverride#10]
Love the extension but this has been happening off and on for a long time. Sometimes after updating Firefox the default focus permanently changes, still other times updating New Tab Override causes it.

I simply would like **about:home** to open and have the cursor in the search bar, not the URL. Why does focus keep changing version after version? Why is it so hard to keep the focus situated?

Custom URL has the option of where to set focus but If I try and enter **about:home** under **Custom URL** it says "This is not a valid URL" and defaults to a blank page.
 
New Tab Override 7.0.0
Firefox 55.0.1

Edit: Also, `extensions.newtaboverride@agenedia.com.focus_website` is set to **true**

**Comment by cadeyrn** [comment]
Thank you for your suggestion.

It's already possible to use the custom url option with focus on website instead of address bar in New Tab Override 7.1.0. I submitted the update to addons.mozilla.org a few hours ago, it's waiting for review.

I'll keep this ticket open to show the option also on the predefined about:home option because there is no checkbox at the moment.

**Comment by grauenwolfe** [comment]
Superb. Vielen Dank.

**Comment by cadeyrn** [comment]
fixed with https://github.com/cadeyrn/newtaboverride/commit/85aafc90f27f11f9666f4a72f53a77e51fc0efa6 and https://github.com/cadeyrn/newtaboverride/commit/5a800e2d4e68e3510603579bfae8cf6d3ff06bb6, will be part of the next feature update after New Tab Override 7.1.0 which also will be released soon.

**Comment by cadeyrn** [comment]
New Tab Override 8.0 has been released.

**Comment by jjzmajic** [comment]
This option has been disabled again it seems

**Comment by cadeyrn** [comment]
Yes, since almost a year. ;-)

https://github.com/cadeyrn/newtaboverride/releases/tag/v14.3.0

**Comment by jjzmajic** [comment]
But the focus is not on the web page anymore. Not on the default Mozilla home page, or the blank page
