### ISSUE TITLE
blinking cursor in the address bar at launch, possible change?

### ISSUE THREAD

**Issue by oxydium** [cadeyrn/newtaboverride#100]
Hello
thank you very much for your superb extension ;)
I set the extension for the new tab to open with this parameter
**"" Set the blinking cursor on the web page instead of the address bar ""**

I wanted to know if it was possible to apply this setting also to the lacement of Firefox?

because the cursor flashing when Firefox is launched is in the green box of my screenshot
http://pix.toile-libre.org/upload/original/1511277475.png

if you know the variable to modify in about: config or a parameter to add in userChrome.css, I'm interested :)

this native behavior of the blinking cursor is not logical ...
why put a search bar in the middle of the page, if the cursor does not go in automatically  :o

thank you in advance
_and sorry for my bad English, I'm French .._

**Comment by cadeyrn** [comment]
Hi,

unfortunately I don't understand your request. If the address bar has the focus, the cursor has to blink. If the web page has the focus, there is no blinking cursor in the address bar.

If the option is selected to set the focus to the web page it's up to the web site to set the focus to a search field on this web page.

**Comment by cadeyrn** [comment]
closed due to inactivity of the reporter. It can be reopened if there is new input.
