### ISSUE TITLE
Access to local files via URL is no longer possible for extensions.

### ISSUE THREAD

**Issue by dEb2LTLY** [cadeyrn/newtaboverride#103]
I have the latest version of New Tab Override 11.0.0, but it does not give me the access to my local *.html files(local web page) on my local harddrive. In the old legacy firefox version before version 57 I could customize local URL like this: file:///C:/myfolder/index.html in both new tab and hompage button but when I use your custom URL I only get an blank page when I set my local page there. The same happens when I use your "Current homepage" function. Your "local file" funtion only load some some of the first index file but not the local links that is to other local links on the index.html. These local links on idex file are not clickable to and does not work. Icons on my local index page are also not working so I hope you will soon fixing this so I can use my whole local web page with many local links like before. The firefox home page function still does work with my whole local web page and all its local links so i therefor hope you will soon be able to make use of it from the home page. Thanks i advance,

**Comment by cadeyrn** [comment]
The local file option in New Tab Override is all what's possible for WebExtensions. You can't use file:// URIs. But you can setup a local web server like XAMPP oder MAMP, this comes without any restrictions and works very well.
