### ISSUE TITLE
Web Extension as New Tab

### ISSUE THREAD

**Issue by FRibadeau** [cadeyrn/newtaboverride#105]
I'm using "**Speed Dial**" and I would have to have it as New Tab page.
The URL is : _moz-extension://e636ad20...00/data/speeddial/index.html_ (without the ..., of course)

It's not working as http:// is always added to the extension.

Can you please correct/change this behaviour ?

**Comment by cadeyrn** [comment]
No, that's not possible for WebExtensions.
