### ISSUE TITLE
JavaScript gets ignored with the local file option

### ISSUE THREAD

**Issue by okapia** [cadeyrn/newtaboverride#106]
As my new tab/home page, I use a local HTML file. Roughly speaking it implements something resembling the traditional speed dial but some JavaScript functions pick certain sites based generally either on the day of the week or time of day. So, e.g. a link for football scores will only be included on Saturday. This worked fine via a different extension before Firefox 57 but now the JavaScript elements don't work.

With New Tab Override, the <script> elements appear to be ignored (otherwise it works fine). I'm no expert but I think this relates to the use of body.insertAdjacentHTML() to populate the DOM tree from the local file. Is there some alternative that would allow this to work? Perhaps just assigning to innerHTML?

I can reproduce the problem fairly simply with a basic HTML file that just uses document.write within a <script> element.

Or do you perhaps have any idea for an alternative solution that doesn't involve hosting the file on a web server? I thought about using XSLT instead of JavaScript but I'm not sure Firefox supports either exslt or xslt 2 which are needed for getting the date/time. Thanks.

**Comment by cadeyrn** [comment]
innerHTML is unsafe and not allowed in Firefox extensions, it was also not allowed in legacy add-ons before Firefox 57. And WebExtensions are not allowed to directly execute local files.

You could use a local web server like XAMPP or MAMP, this comes without any restrictions. Then all you have to do is to use the custom url option and use you localhost address.

**Comment by okapia** [comment]
Ok, thanks. I was hoping there would be some other solution. Running a local web server is not an option on my work desktop. Is there not some way to provide even a limited hook from local_file.js? Perhaps scanning for the script element and using eval()? Or even loading a separate file with browser.storage.local.get?

I had used "New Tab Homepage" as the legacy plugin and perhaps because it was just loading my home page it was unaffected by this limitation. Unfortunately, New Tab Override with the home page doesn't solve this.

**Comment by cadeyrn** [comment]
I can have a look if insertAdjacentHTML() is the reason and if there is an working alternative but I don't know if it's possible or if there is a security restriction for WebExtensions. It will take a few days because I am very busy with private stuff at the moment.

**Comment by cadeyrn** [comment]
I was not able to get this working with the Content Security Policy of Firefox. If someone else is able to get this working I accept a pull request. But in the meantime I have to close the ticket because I don't see a solution.

**Comment by okapia** [comment]
Thanks for giving it a try nevertheless.

**Comment by albegadeep** [comment]
Has this been reassessed in the last 2 years? Is there no way for javascript, embedded in a local HTML file, to run?

**Comment by cadeyrn** [comment]
This is still valid:

> You could use a local web server like XAMPP or MAMP, this comes without any restrictions. You don't need to host the file on a remote web server. Then all you have to do is to use the custom url option and use your localhost address. The file is still local on your system and not accessible via the web.

**Comment by albegadeep** [comment]
Unfortunately, like okapia, I can't run a local web server on this machine.

**Comment by cadeyrn** [comment]
Then you have to upload your new tab page somewhere. The "local file" option of New Tab Override is very limited and covers some simple use cases but more advanced use cases are not possible with local files.
