### ISSUE TITLE
"New Tab" in titlebar 

### ISSUE THREAD

**Issue by pdqpat** [cadeyrn/newtaboverride#108]
Addon would be perfect if you replace "New Tab" in titlebar with the page title

**Comment by cadeyrn** [comment]
I don't know what you mean. If, for example, Google is your new tab page then Google is in the page title. Please provide more details.

**Comment by pdqpat** [comment]
I use a local file as my home page.  I don't mind the internal url (moz-extension://5c40846e-b887-4f3d-ab0b-dea561b8cfaa/html/local_file.html) but it ignores the page title "START PAGE" and says "New Tab". Niggly I know. ;)

**Comment by cadeyrn** [comment]
Thank you for the explanation. It makes sense to extract the <title> attribute. I will investigate this as possible enhancement for a future update.

**Comment by pdqpat** [comment]
Awesome work and thank you.  I'm slowly finding replacements for missing addons - but sadly not for Tab Mix Plus.

**Comment by cadeyrn** [comment]
Fixed in development version of New Tab Override 12.0.

**Comment by cadeyrn** [comment]
New Tab Override 12.0 has been released a few moments ago.

**Comment by pdqpat** [comment]
Great work.  After struggling with the new Firefox, I wonder how the built-in "home" icon can load a local home page (right over the current tab - nasty!) but nothing else can -- except your addon of course.
