### ISSUE TITLE
New tab override cannot focus on address on Firefox for Mac

### ISSUE THREAD

**Issue by liaowang11** [cadeyrn/newtaboverride#109]
When "new tab override" is enabled, 
1. open firefox and Command+t to open new tab
2. tab openned and the **focus is on the address bar**
3. toggle **Full screen** under **View** menu( or Ctrl+Command+F)
4. open new tab
5. tab openned but **the focus is on the page not the address ba**r

**Comment by cadeyrn** [comment]
I cannot reproduce. There is no difference between full screen and regular screen, in both cases the focus is on the address bar after opening an new tab. Tested with google.com as new tab page.

**Comment by liaowang11** [comment]
I'm using Firefox Nightly, maybe that's the reason. Will try firefox 57 to see.

**Comment by cadeyrn** [comment]
I'm using Firefox Nightly on macOS, too. ;-)
