### ISSUE TITLE
Allow custom about:xxxxxxx URLs

### ISSUE THREAD

**Issue by Chilledpeperami** [cadeyrn/newtaboverride#11]
I use bookrect as a basic list of my preferred shortcuts and use new tab override to set my new tabs to open to that.

However with the new update it won't allow me to set the new tab URL to "about:bookrect".

**Comment by cadeyrn** [comment]
only http(s) pages and a small subset of about: pages are allowed as new tab page for WebExtension. Additional with Firefox 57 it's no longer possible for add-ons to use "about:something" as URL. New Tab Override 7.0 was developed from the ground up to make it compatible with Firefox 57 and higher. Firefox Nightly is already on version 57.
