### ISSUE TITLE
Adding an option for opening new tab next to current

### ISSUE THREAD

**Issue by lezab** [cadeyrn/newtaboverride#110]

**Comment by cadeyrn** [comment]
There is no WebExtension API for that. It will be possible after https://bugzilla.mozilla.org/show_bug.cgi?id=1344749 is fixed.

**Comment by lezab** [comment]
ok, thanks, i'm gonna wait for it

**Comment by stervel** [comment]
I use Always Right for that.

**Comment by cadeyrn** [comment]
well, add-ons like Always Right and Open Tabs Next to Current show that it's possible with complicated and ugly workarounds to get this enhancement implemented right now. But since there is a nice API in development I will wait for this API.

**Comment by lezab** [comment]
The bug you talked about seems to be resolved now. Am I wrong ?
However, by setting "browser.tabs.insertAfterCurrent" option to true in "about:config", I have the required behaviour, so perhaps there's no need to add this option to the extension.

**Comment by cadeyrn** [comment]
Yes, the API has been implemented. I guess since there is an API it would be nice to implement an option in New Tab Override so that users don't have to change things in about:config.

**Comment by cadeyrn** [comment]
@lezab: New Tab Override 15.0 was released and it includes your requested feature. Thanks for suggesting it!
