### ISSUE TITLE
S/B OK for new tab page URL to match Home Page, even if it's local

### ISSUE THREAD

**Issue by DBDrane** [cadeyrn/newtaboverride#111]
The browser opens Home Pages, why can't New Tab Override?

**Comment by cadeyrn** [comment]
It's not the job of New Tab Override to handle the home page, your description does not make sense. I don't know what "S/B OK" in the title means. You say something with "local" but the descriptions in the add-on already say all what can be said about this topic.

**Comment by DBDrane** [comment]
Thank you for answering my suggestion. I'd like to explain my suggestion as I clearly was unclear before. 
Of course I realize that it may be impossible for you to implement it due to Firefox restrictions. I am hoping that you will agree that my suggestion is reasonable and you might be willing to get the message to Firefox, 

"S/B OK" is American shorthand for "should be OK", that is, "should be good". By "local file" I meant a file on my local computer, the computer on which Firefox is running. I prefer that my home page be a file on my local computer, one that I maintain myself which contains links to about 200 websites that I use most frequently. (I started this when I used browsers at home and I accessed the web using modems at 9600 bps, which was painfully slow.) It's been my home page ever since. You can see the public part of my desired home page here: http://home.wavecable.com/~drane/remote.html . It is the same as my local home page with the links to local files removed. 

In the New Tab settings you said "Please note: Access to local files via URL is no longer possible due to Firefox restrictions. Please consider using the “local file” option or a local web server, for example via MAMP or XAMPP. 

When I execute Firefox it opens and displays my home page using this URL: file:///C:/Users/drane/home/etc/index.html . To me it seems illogical that I cannot make the same URL be used for opening new tabs. 

I made my suggestion with a slight hope that this blanket restriction might be relaxed a bit. But really, for me it's a minor inconvenience for me to have to open my home page immediately after each new tab. I'll get used to that.) 

- Dorsey Drane 

----- Original Message -----

**Comment by cadeyrn** [comment]
Thank you for the explanations.

Unfortunately I don't have any influence in the development of Firefox. I already expressed my voice in Mozillas bugtracking system for all what I want for New Tab Override.

I recommend to set-up a local web server like XAMPP or MAMP because it's not difficult and it works. Then you don't have to make your new tab page public for the whole world.
