### ISSUE TITLE
Flashes white background even when using DARK theme

### ISSUE THREAD

**Issue by JimDop** [cadeyrn/newtaboverride#112]
This really isn't a bug, but maybe you could figure out how to avoid the very annoying white screen that flashes before turning to  black  on a new tab. 

 Probably the way the screen is drawn in Firefox .   Maybe could force black before anything gets displayed?

**Comment by cadeyrn** [comment]
Please set browser.display.background_color in about:config to the desired color (in hex format) to avoid the flickering. I opened a ticket on Mozilla's bugtracking system to suggest a API to override this option in a WebExtensions. At the moment WebExtensions can't change this option.

**Comment by aesthicc** [comment]
Thanks.
Changing > browser.display.background_color
Doesn't fix it for me though.

**Comment by cadeyrn** [comment]
why not? You can change it to every color you want. If it's the same color as your new tab page then there is no flickering.

**Comment by aesthicc** [comment]
Idk I set it to #000000 and there's still a white flicker.

**Comment by aesthicc** [comment]
I was trying different things so i also have:
tabbrowser-tabpanels {
	background-color: #000000 !important;
}
&
browser[type="content-primary"], #content, browser[type="content"] > html {
    background: #000000 !important;
}

In my userChrome.css
There's something i'm missing
It seems to be going black->white->black->actual page but it's too fast to be sure.
