### ISSUE TITLE
Adding an crash recovery feature for tabs.

### ISSUE THREAD

**Issue by ChibiSqueaks** [cadeyrn/newtaboverride#114]
If possible I think adding a crash recovery feature for your tabs would be great. Like if firefox crashed you would be able to recover the open tabs that you had before the crash.

**Comment by cadeyrn** [comment]
But why on the new tab page for every new tab?

**Comment by ChibiSqueaks** [comment]
I just figured since this extension deals with tabs that it could be an option. If I was wrong then please disregard. ^.^

**Comment by cadeyrn** [comment]
This extension does only deal with the new tab page of Firefox, that's why the name is "**New Tab** Override. ;)
