### ISSUE TITLE
New Tab Override - Can't make it work FF 57.0.4

### ISSUE THREAD

**Issue by NewTabDoesNotWork** [cadeyrn/newtaboverride#117]
What do I need to do or am I doing wrong?
Firefox 57.0.4
Added the newtaboverride addin
Provided the desired permissions
Configured to open to customer url https://www.google.com/
Restarted firefox
restarted computer
When I click on + (PLUS) sign to add new tab still getting my typical Home page
Attached my settings

![my settings](https://user-images.githubusercontent.com/35179011/34645302-45c1817c-f30f-11e7-9b24-5d29043e1724.JPG)
![my add ons](https://user-images.githubusercontent.com/35179011/34645303-47ffd2f4-f30f-11e7-89e1-a7b80bd3c1b6.JPG)

**Comment by Mishkatel** [comment]
I can't get NewTab override to work either. I want every New Tab to open with my home page which is  file:///C:/!Home.htm   Should be simple but find the interface confusing. getting too old I guess...
Thanks for any easy to understand help with step by step instructions...

**Comment by cadeyrn** [comment]
@NewTabDoesNotWork: Please test with other add-ons disabled. You can use only one (!) add-on which is trying to manage the new tab page. Your screenshot shows two such add-ons.

@Mishkatel: Please read the descriptions within the add-on regarding local file access.

**Comment by cadeyrn** [comment]
closed due to inactivity.
