### ISSUE TITLE
Glass

### ISSUE THREAD

**Issue by twisted3313** [cadeyrn/newtaboverride#118]
not an issue but was wondering if i can make the background see thru

**Comment by cadeyrn** [comment]
what do you mean?

**Comment by twisted3313** [comment]
Like in this picture just pure glass on newtab or "aero theme"

**Comment by cadeyrn** [comment]
There is no picture in your comment.

Also it does not really make sense. Where should the glass be? The browser is not transparent, you can't look through the browser.

**Comment by twisted3313** [comment]
here i sent it thru email but did not go thru 
https://ibb.co/b2xj96

**Comment by cadeyrn** [comment]
It's not possible to look through the browser, so I can't implement such an option. Solid colors are the only option.

**Comment by twisted3313** [comment]
https://userstyles.org/style_screenshots/59277_after.jpeg

**Comment by twisted3313** [comment]
i have been able to get all glass when i open new page a cancel it before it loads
https://ibb.co/cLA9CR  but not when i open newtab

**Comment by twisted3313** [comment]
nevermind this guy helped me 
It should work, if you install an older Stylish version (2.1.1). Version 3 is a huge step back feature-wise because of WebExtension limitations, but you don't have to use it on Firefox 56 and older or on forks like Waterfox.
For me Stylish developers move to set 3.x versions minimum browser compatibility below 57 does not make any sense. Even if Firefox 48+ is technically capable of running WebExtensions, it is deeply wrong to force v3.x on users of Firefox 52 ESR, Basilisk or Waterfox knowingly robbing them many great features in advance.

**Comment by cadeyrn** [comment]
userstyles are for the userChrome.css file. WebExtensions don't have access to the browser CSS of Firefox.
