### ISSUE TITLE
cursor not placed on the web page despite the selected option

### ISSUE THREAD

**Issue by melmelissa** [cadeyrn/newtaboverride#119]
Hello

when the option

**default homepage of firefox (about: home)
is activated**

and the box (ticked)
 
**Set the flashing cursor on the web page instead of the address bar**

the cursor has no focus anywhere.
if the box is unchecked, the cursor has the focus in the address bar.

the problem is with Firefox Nightly on Debian Sid and ArchLinux.

Am I the only one ??

**Comment by melmelissa** [comment]
I'm the only one??
I have not seen a hidden option that solves the problem ???
it interests anyone ???

I thought that github was used to trace the bugs, to talk with the maintainers and try to correct the problems, given the silence ..................

**Comment by cadeyrn** [comment]
Really? You can't wait two days for an answer? I have a full-time job. This add-on is developed in my spare time…

**Comment by melmelissa** [comment]
I too have a full-time job, with trips all week, and a family to take care of, and I take 5 minutes to answer you even...
 if it does not solve the bug report....

if I am here, it is to raise a bug, and to hope a correction on the part of its maintainer ...
but if the manager does not want it, it does not matter; it's just him who will have a bad image with regard to these users, it's not me ...
the extension is good, but tracing a bug towards you, is apparently complex ...

the archlinux and debian maintainers also take their free time, yet a bug is repaired within 24 hours, even if it is minimal.
  but their responsibilities are important..

since my bug report is bothering, I'll see elsewhere, I'm not complicated as a girl :D

**Comment by cadeyrn** [comment]
can't reproduce, works for me.
