### ISSUE TITLE
Own file as a new tab page?

### ISSUE THREAD

**Issue by edenprojectde** [cadeyrn/newtaboverride#12]
Since my nightly updated i cant use my own index.html as an New Tab Page. That was the sole purpose for the Extension for me. :/

**Comment by cadeyrn** [comment]
As already said in all the other tickets: WebExtensions are not allowed to load local files via file:// protocol as new tab page. You have to upload your file or to use a local web server. You could use XAMPP or MAMP do achieve this.

**Comment by cadeyrn** [comment]
New Tab Override 8.0 has a new "local file" option. It's not perfect but it's the best possible solution.

**Comment by edenprojectde** [comment]
@cadeyrn Would it be possible to upload a zip, or some other container that holds the images of the html page as well?
It doesnt need to load in php or stuff like that. Just simply the images, css and the main html page in a container to use it like before.

**Comment by cadeyrn** [comment]
It's not possible because in the HTML file there have to be references to other files to show these files. And you can't reference other local files via an URI so even if the other files are stored in the extension's storage, the HTML file from the storage can't access these.
