### ISSUE TITLE
Firefox Add-on 'New Tab Override' option selected 'Current Home Page' does not work

### ISSUE THREAD

**Issue by NashvilleKit** [cadeyrn/newtaboverride#121]
I have Firefox 58.0 running on Win10. I added the Add-on 'New Tab Override' and selected the Option of 'current home page.' This simply does not work; I open a New Tab and I get Nothing - a blank screen.

**Comment by cadeyrn** [comment]
I can't reproduce, works here without any problem. Please show me your homepage settings.

**Comment by NashvilleKit** [comment]
My home page is a local HTML file I built for myself.
The link reads something like:
 
file:///C:/MyStart/index.html <file:///C:\MyStart\index.html> 
 
(I also have several other local files
Is it's "localness" the problem??
 
If so, it's still a problem that I formerly resolved using a now-legacy add-on called something like "Home Page on New Tab."
 
Now I must click the home page icon every time I bring up a new page. Ridiculous. I HATE this Quantum change!!! 
 
I'm even starting to use Chrome more and more now. I'm about ready to switch to it as my default browser. Their extension "New Tab Redirect" works perfectly with my local file.
 
But, thanks for getting back to me.
 
NashvilleKit
http://www.kitwilliams.com

**Comment by cadeyrn** [comment]
There is no problem to setup a local server like XAMPP or MAMP and use this for local file acces. This works for local files. There is no reason to be angry about Firefox because it's still doable.

In New Tab Override I can't provide better support for local files.

**Comment by NashvilleKit** [comment]
Sören,
 
I apologize, but I don't have the resources to setup a WAMP or Xampp server. I shouldn't have to spend the money to set up an entirely separate computer just to test my simple HTML coding for my website (my retirement hobby); local files work perfectly fine. I do not use PHP at all and that is what these types of local servers are used for, not for making "local home pages" work with your add-on.
 
Ben Basson's 'New Tab Homepage' is – according to the developer – supposed to deal with a local home page. But a Firefox bug is keeping it from working, so he says. So, I'm stuck having to click on the homepage icon every time I start a new tab. And your comment about being "angry about Firefox" is inexcusable – you're right, I AM angry that the developers have done this to me. I've been a loyal Mosaic/Netscape/Mozilla user since I met with Jim Clark to develop some of the first e-commerce servers in 1994. I think I've earned the right!!
 
It all works fine on Google's Chrome and I would switch over, but I don't like Google knowing any more about me than they already do!!
 
I can see absolutely no reason why most of my favorite add-ons are now "legacy." Ever since Ver. 57, the so-called Quantum release, I've tried unsuccessfully to revert to Rev. 56. the last decent release!
 
So there,
 
NashvilleKit
Christopher H. "Kit" Williams
http://www.kitwilliams.com
kitwms@gmail.com

**Comment by cadeyrn** [comment]
> I apologize, but I don't have the resources to setup a WAMP or Xampp server. I shouldn't have to spend the money to set up an entirely separate computer just to test my simple HTML coding for my website (my retirement hobby)

Which resources? Which money? You need less than five minutes and no money. Either you want to use a local file or you don't want it (enough). But don't tell me that there are insurmountable hurdles. I know that this is not true.
