### ISSUE TITLE
white flash when loading new tab

### ISSUE THREAD

**Issue by aesthicc** [cadeyrn/newtaboverride#122]
When using a dark theme/dark homepage, newtaboverride briefly causes a white flash when loading a new  tab. I am unable to resolve this for the newtabovveride custom new tab page using userChrome.css or userContent.css.

**Comment by cadeyrn** [comment]
Please see this comment to solve your issue:
https://github.com/cadeyrn/newtaboverride/issues/112#issuecomment-353940482
