### ISSUE TITLE
Return to last tab via click on current tab

### ISSUE THREAD

**Issue by ghost** [cadeyrn/newtaboverride#123]
I would like to be able to return to the last tab by simply clicking on the current tab. We lost this feature with FF 57.0. This is a great feature that others have talked about online. If you can do it, great!! Bob

**Comment by cadeyrn** [comment]
How exactly does this fit into New Tab Override? New Tab Override changes what Firefox opens as new tab.

**Comment by rjlavender** [comment]
It does not directly fit. But, perhaps, you could create a new add-on. There was a popular add-on called Focus Last Tab that did this but it no longer exists.

 

Can you create a new add-on for us?

 

Thanks!

 

Bob

**Comment by cadeyrn** [comment]
Sorry, I don't have plans to create another add-on for tab management until there are better tab APIs. Once I am really happy with New Tab Override I can reconsider this and maybe create a more advanced tab extension.
