### ISSUE TITLE
selecting URL bar

### ISSUE THREAD

**Issue by exekutive** [cadeyrn/newtaboverride#124]
I understand the trouble with Mozilla support on this (https://bugzilla.mozilla.org/show_bug.cgi?id=1409675).

However, I can select the URL with the keyboard shortcut 'command-L'. Is it not possible to program a macro into your extension which simulates this key combination?

**Comment by cadeyrn** [comment]
No, that's not possible for WebExtensions.

**Comment by nonong1191** [comment]
If you are just wanting to delete the url in the address bar so that you can start typing in a new one, then you can pseudo-accomplish it by choosing Custom URL and just put a space for the custom url.  Then when you open a new tab, you can start typing away.  Enjoy!

**Comment by cadeyrn** [comment]
New Tab Override has an option for an empty new tab page with an empty address bar, there is no need for such a workaround. But there is not way to select the URL of empty the address bar if you want another website as new tab page.

**Comment by earthbound19** [comment]
@nonong1191 at this writing that workaround is incompatible with the option to have a solid background color. In that case I set it to focus on the web page (not the address bar), and it auto-selects the URL in the address bar when I click on it, so I can just type over and it clears the address bar.
