### ISSUE TITLE
White flash

### ISSUE THREAD

**Issue by ghettoparazite** [cadeyrn/newtaboverride#125]
The infamous white (background) flash that happens when you load a new tab or clicking on a idle tab can be remedied by adding the below into <firefox profile>/chrome/userChrome.css.

`.browserContainer { background-color: #000000 !important; }`

However, when using your addon the white flash is still there, albeit for a shorter time, when loading a new tab (set to load a custom URL). If I disable the addon the white flash is gone. So, would you please add a option to set which background color you want at the very beginning of your addon to minimize or even remove the white flash happening?

**Comment by cadeyrn** [comment]
You have to change browser.display.background_color in about:config if you want to set the white color to another color.

It's not possible for WebExtensions to change that.
