### ISSUE TITLE
add more messaging around the "local file access" topic

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/newtaboverride#13]
Because 1000 messages are not enough, let's add a 1001. message that local files are no longer supported.

**Comment by billbaldwin2** [comment]
I probably missed it in the 1000 messages. But is it not possible to have the new tab set to open the home page specified in General preferences? I have my home page set to a local file and it works just fine. It's hard to wrap my brain around the idea that there's no way for an extension to tell Firefox to open a new tab and display the home page.

I can open up a new tab with my home page by ctrl-clicking or middle-clicking on the home page icon. But of course I'd rather do it by clicking on the new tab plus sign (or using ctrl-t).

**Comment by cadeyrn** [comment]
> But is it not possible to have the new tab set to open the home page specified in General preferences?

It will be possible in a future update of Firefox (Firefox 57 at the earliest) but it's not possible in Firefox 55 and Firefox 56.

**Comment by cadeyrn** [comment]
more messaging added in New Tab Override 8.0.
