### ISSUE TITLE
Firefox window color

### ISSUE THREAD

**Issue by exekutive** [cadeyrn/newtaboverride#131]
When you open a link in a new tab (either via right-clicking, or the keyboard shortcut), the first thing you see is white. Even if you choose the dark theme in Firefox, it will be white. And sometimes it can linger a while, before the page background loads. Indeed this is even the case for this extension, since it is just loading a background.  I find that a dark background is much easier on the eyes, especially when using the computer at night.

It would be great if this extensions could change this default window color.

**Comment by cadeyrn** [comment]
You can change browser.display.background_color via about:config to another background color. It's not possible for WebExtensions to change this option.

**Comment by exekutive** [comment]
it didn't work for me

**Comment by exekutive** [comment]
Figured it out. You have to change 'browser.display.use_system_colors' to false.

**Comment by cadeyrn** [comment]
It always worked and it still works. If I set browser.display.background_color to #ff0000 and set the new tab page to a arbitrary website in New Tab Override the background is first red (because of #ff0000) before the content is loaded.
