### ISSUE TITLE
Add option to reload local file every time new tab is created

### ISSUE THREAD

**Issue by arnm** [cadeyrn/newtaboverride#132]
I make changes to the local file I'm specifying and I want the changes to be displayed when I open a new tab. I currently have to specify the file again for the changes to be reflected in a new tab.

**Comment by cadeyrn** [comment]
Then you have to set-up a local server like XAMPP or MAMP and use the custom URL option. There is no other way.

**Comment by arnm** [comment]
That is a possibility. I already have a custom local serving running so that wouldn't be anything new for me.

I'm guessing the storage API can't help in this scenario? Where the user defines a file on the file system and the extension can freely access it. I assume the storage API has some predefined location where it can manage those files.

**Comment by cadeyrn** [comment]
WebExtension don't have access to local files at all (except one option, see next sentence) so they can't watch for changes of local files. The local file option in New Tab Override uses a workaround: it allows you to "upload" a local file in the add-on's storage. But this means that you have to re-upload your file after changes. A local server is really the only option for your use case.
