### ISSUE TITLE
Remove "about:blank" from the address bar

### ISSUE THREAD

**Issue by LordZane** [cadeyrn/newtaboverride#133]
I set my new tab page to about:blank, and it focuses on the address bar, but if I try to search "firefox", I end up with "about:blankfirefox". Can you remove the about:blank please?

**Comment by LordZane** [comment]
Yeh that works for now, ill leave this open for now I guess. Im running 60.0b4 (64-bit) normal firefox

**Comment by cadeyrn** [comment]
will be fixed in New Tab Override 13.0.0.

**Comment by cadeyrn** [comment]
New Tab Override 13.0.0 has been released.
