### ISSUE TITLE
Focus is not set on the about:home search bar

### ISSUE THREAD

**Issue by cephira** [cadeyrn/newtaboverride#134]
I am using Firefox 59.0.1 and New Tab Override 12.0.0 on Windows 7 and recently noticed that the cursor is not in the search box of the about:home page. I have checked "Set focus to the web page" and this used to work fine. The focus *is* being set to the web page (not the URL), but it is set to the entire page and not the search bar. My default home page has everything disabled except the search bar, though it also shows the Firefox "Let's get started" tour icon in the upper-left and the settings gear icon in the upper-right.

Typing and/or hitting enter have no effect when I first open a new tab. If I press tab my focus moves to the "Let's get started" button, and if I press tab again my focus moves to the search bar. If I then press shift-tab the focus goes back to the "Let's get started" button, and if I press shift-tab again the focus highlight is drawn around the entire web page frame.

I tried disabling all other add-ons as well as disabling and re-enabling New Tab Override but it didn't change anything.

I also tried setting New Tab Override to use www.google.com and the focus is on their search bar as expected. I am using this as a workaround for now.

**Comment by alphestdev** [comment]
Experiencing the same, in FF59 and now FF60 after update. 

**about:home** does not receive focus in the search bar.  I use your addon for this only reason, to put the focus inside the search bar automatically.  But it doesn't do the job it promises.

Please fix this if you can.  If it works for other sites, but doesn't for about:home, maybe create a custom rule for about:home?

**Comment by cadeyrn** [comment]
There is nothing I can do.

**Comment by alphestdev** [comment]
In the software world there is always something to do about a problem. Just saying.

**Comment by cadeyrn** [comment]
@alphestdev: Your comment is pure nonsense. WebExtensions can only do what Firefox allows them to do. It's a lie when you say there's always something you can do about a problem.
