### ISSUE TITLE
Add Spanish ES-es Translation

### ISSUE THREAD

**Issue by MissingUser** [cadeyrn/newtaboverride#135]
Find attached Spanis translation.
[messages_json.txt](https://github.com/cadeyrn/newtaboverride/files/1843225/messages_json.txt)

Please consider to include it.

**Comment by cadeyrn** [comment]
Thank you very much! I added the translation to New Tab Override 13.0.0, to be released soon.

**Comment by cadeyrn** [comment]
New Tab Override 13.0.0 has been released.
