### ISSUE TITLE
newtaboveride does not work with Quantum 59.0.2

### ISSUE THREAD

**Issue by tbav** [cadeyrn/newtaboverride#137]
Changing the options in the new tab overide add on has no effect on new tab home pages.  This add on worked with 58.x.x versions of Quantum.  I simply want new tab pages to open to my home page, trivial functionality which I am amazed is absent in Quantum.

**Comment by cadeyrn** [comment]
Please provide more information about your configuration otherwise I won't be able to help.

**Comment by cadeyrn** [comment]
closed due to inactivity.

**Comment by tbav** [comment]
Soren:


FYI, it began magically working with the latest Quantum update.


________________________________

**Comment by cadeyrn** [comment]
Great to hear!
