### ISSUE TITLE
New Tab Override for simple local file does not seem to work

### ISSUE THREAD

**Issue by jotaf98** [cadeyrn/newtaboverride#138]
Hi, I'm trying to get New Tab Override to work on a local page. To make it as simple as possible, I'm testing this HTML file:

```
<html>
<head>
</head>
<body bgcolor="#FF0000">
</body>
</html>
```

If it had worked, the page would be red; instead it's white. I tried web URLs and the "background color" options, and they seem to work fine; it's just a local file that doesn't work.

Checking the browser console, from the moment I open a new tab, there are several errors:

```
TypeError: Argument 1 of StructuredCloneHolder.deserialize is not an object.[Learn More]  ExtensionChild.jsm:897:24
Error: Missing host permission for the tab undefined
Cannot send function call result: other side closed connection (call data: ({path:"history.deleteUrl", args:[{url:"moz-extension://4a5f1a1b-926b-4dda-a5f4-3fc9dc6c9180/html/newtab.html"}]}))
Error: Missing host permission for the tab undefined
```

I'm using FF 59 on Ubuntu 16, and I have only a few addons, namely uBlock and Self-Destroying Cookies. I tried disabling them but that didn't help.

**Comment by Henryvw** [comment]
Hi, I have also noticed this problem. It appears that `extension/local_file.html` is currently hard-coded to a string or constant `local_file.html' instead of a variable that fills in the relevant local html file.

**Comment by cadeyrn** [comment]
That's not a problem, that's the only way for a WebExtension to provide such an option.  On the options page you can store the content of your local file in the storage of New Tab Override. The file local_file.html is the new tab page and loads the content from the storage.

A local server like XAMPP or MAMP is really the better option if you want to use local files as new tab page without any restrictions.

**Comment by Henryvw** [comment]
Thanks kindly for the swift response. Then maybe the storage is failing? Something isn't working. Thanks for the MAMP suggestion, yes I saw that was another option. I may look into that!

**Comment by reflecx** [comment]
New Tab override for local file seems to have stopped working with version 14.0, tested on Firefox 61 and 62. All I get is a blank new tab, nothing in the URL or the title.

**Comment by cadeyrn** [comment]
Thanks for reporting. I have to test it but I have an idea why this happens. If my idea is right I will have a bugfix later today.

**Comment by jotaf98** [comment]
Thanks for looking into it!

Unfortunately with New Tab Override 14.0.2, following the same steps still has the same result (the page is blank, the source code for it is also blank). Using FF 61.

Browser Console errors when opening a new tab:
```
Cannot send function call result: other side closed connection (call data: ({path:"tabs.remove", args:[101]}))
Cannot send function call result: other side closed connection (call data: ({path:"history.deleteUrl", args:[{url:"moz-extension://b43c4d45-a9ed-4019-afcf-469608a8d1e1/html/newtab.html"}]}))
```

**Comment by cadeyrn** [comment]
Hi,

only the issue raised by reflecx nine days ago has been fixed, not the original report. I still have to look into this, that's why this issue is still open. But I don't think there is much I can do. There are a lot of security restriction for local files. I have to summerize what is allowed and what is not allowed.

The easiest way is to setup a local server like XAMPP or MAMP and use the custom url option of New Tab Override.

**Comment by jotaf98** [comment]
Thanks, yes I know it's very restrictive. Maybe one way to work around them would be to read the HTML content and inject it into the addon's own tab page (like a content script, which can edit HTML at will). As opposed to directing the URL to a file, which seems to be heavily restricted.

**Comment by cadeyrn** [comment]
The local file option already works this way. The content ist stored in the add-on's storage and on new tabs the content stored in the storage is injected into an internal page of New Tab Override. But it's possible that inline styles are also blocked. You could try to do something like:

```
<style>
  body {
    background-color: #FF0000;
  }
</style>
```

instead of

`<body bgcolor="#FF0000">`

I have to try what is allowed and what is not allowed but maybe this works. I didn't test this.

**Comment by Ben-Voris** [comment]
When I select a the local file option, navigate to a html file, and open a new file, I see this in the console of the new tab:
```
New Tab Homepage was unable to load your homepage 'file:///E:/public/home.html' redirect.js:70:9
redirectUser/<
moz-extension://a572a66f-c61b-47c6-b18f-9a121ab99c45/redirect.js:70:9
```

Firefox 62.0, New Tab override 14.1.0

If I paste `file:///E:/public/home.html` into the address bar of a new tab, it opens, so the file name is valid.

**Comment by cadeyrn** [comment]
Hi,

this has nothing to do with the issue reported here. WebExtensions are not allowed to open file:// URIs. It's also explained within New Tab Override. The easiest way is to use a local server like XAMPP or MAMP, this comes without any restrictions.

**Comment by Ben-Voris** [comment]
Why does the extension offer local file? When I specify a local file, the error shows it in URL format, but that’s not what I’m doing.

**Comment by cadeyrn** [comment]
I don't understand your comment. The local file only offers a upload field for uploading a simple file without any references to other local files. There is no support for file:// URIs at all. And again: it has nothing to do with this issue.

**Comment by cadeyrn** [comment]
@jotaf98:

Attributes on the body element like bgcolor or style don't work because the content of your uploaded file will be injected into the body area of the internal New Tab Override document and Firefox only interprets the outer body element.

But the following in your HTML works:

```
<style>
  body {
    background-color: #FF0000;
  }
</style>
```

Also inline styles like the following work:

<div style="background: yellow;">A<br>B<br>C</div>

… but as I said not for the body element of your HTML.

**Comment by milanecode** [comment]
Still can't use it, even if I upload a local file. I only get a blank tab.

**Comment by cadeyrn** [comment]
This issue is closed. If you experience problems please open a new issue and provide relevant information (Firefox version, New Tab Override version, your local file or a similar test case). Thank you.
