### ISSUE TITLE
Add option to show Bookmarks Panel

### ISSUE THREAD

**Issue by neomodern** [cadeyrn/newtaboverride#140]
I'm a previous user of addon Bookmark Tab and there's currently no WebExtension version for it, nor alternative that is comparable.

However the inbuilt Bookmarks Panel is acceptable and it would be great to be able to access it via New Tab Override: chrome://browser/content/bookmarks/bookmarksPanel.xul

**Comment by cadeyrn** [comment]
That's not possible for WebExtensions. WebExtensions can only open websites via https:// or http://.
