### ISSUE TITLE
Pinned tabs get changed to custom new tab on reboot

### ISSUE THREAD

**Issue by LeviBrunette** [cadeyrn/newtaboverride#142]
Firefox Quantum 59.0.3
Windows 10 April Update (171341.1)
Surface Book 2 i5

I have Google Play Music as a pinned tab in my browser, but whenever i close the browser and then come back, it doesn't load back to GPM, instead to my custom page.

**Comment by cadeyrn** [comment]
New Tab Override is not responsible for session restores in Firefox, there is nothing I can do.
