### ISSUE TITLE
Minor graphical issue when set to about:blank.

### ISSUE THREAD

**Issue by Peacock365** [cadeyrn/newtaboverride#143]
Hey cadeyrn,

I want to report a small issue that occurs when the setting about:blank is used. When you check the second option (focus on the page instead of the address bar), the tab opening animation is rather glitchy. The effect is weird, I hope you can see it too when the the checkbox is ticked. Firefox 60 Beta, macOS High Sierra, New Tab Override 12.0.0. I don't know if this is an issue of Firefox or of the extension itself. Still, it might be useful to report it here.

All the best

Peacock365

**Comment by cadeyrn** [comment]
Hi,

I had to remove the option "focus on the page instead of the address bar" for about:blank because of issues in Firefox 60 and higher.
