### ISSUE TITLE
A workaround for "The automatic emptying of the address bar or selecting the URL"

### ISSUE THREAD

**Issue by tst2005** [cadeyrn/newtaboverride#146]
Hello

Like many people, I searched to get a (empty) newtab with **empty** addresse bar.

I read :

> The automatic emptying of the address bar or selecting the URL is currently not possible for WebExtensions. This requires a change by Mozilla. [Learn more](https://bugzilla.mozilla.org/show_bug.cgi?id=1409675)

I got the expected result with a Custom URL with an anchor like `about:blank#`.

I don't know if it is a bug, a side effect or if something changed in firefox.

I use: Firefox 60.0.1 (64bits, Linux)

Regards,

**Comment by Rec-U-Drop** [comment]
"The automatic emptying of the address bar or selecting the URL is currently not possible for WebExtensions. This requires a change by Mozilla."

What the hell does that mean — Mozilla doesn't want their users to enjoy the freedom of opening a blank window/tab? Why on earth would they do that? What's wrong with them!?

**Comment by cadeyrn** [comment]
Your workaround has nothing to do with the quoted sentence. You can read this sentence with the "custom url" option selected, it's not about empty new tabs.

**Comment by cadeyrn** [comment]
yeah, something has changed in Firefox 60. I have to release an update to fix the "empty tab" case.

**Comment by tst2005** [comment]
Thanks!

**Comment by cadeyrn** [comment]
New Tab Override 13.0.0 has been released.
