### ISSUE TITLE
"New Tab' on Firefox Not Working

### ISSUE THREAD

**Issue by flubbster** [cadeyrn/newtaboverride#147]
I tried to put in https://www.google.com or http://www.google.com not working.
It did work at first but stopped working. Not sure what to do. Thanks!

**Comment by cadeyrn** [comment]
works for me. please show your add-on's settings, thank you.

**Comment by flubbster** [comment]
How do I show them? I tried to copy, didn't work.
Thanks for your response!

**Comment by cadeyrn** [comment]
you can make a screenshot of the settings page and attach it to this GitHub issue or use an image hoster and share the link of the uploaded image.

**Comment by flubbster** [comment]
I tried options:
1) current home page and
2) custom urlI'd like the new tab to be https://www.google.com/

**Comment by flubbster** [comment]
You are the author! Thanks for responding.I am getting a blank page instead of Google.

**Comment by cadeyrn** [comment]
Tested again, Google works without any problems for me. Tested with custom url option and as home page with the option to use the home page as new tab page.

**Comment by flubbster** [comment]
Thanks, working now! I love it, thanks!!!
