### ISSUE TITLE
New Tab Override settings are not being saved when the extension's "Options" tab is closed.

### ISSUE THREAD

**Issue by Mario3264** [cadeyrn/newtaboverride#154]
New Tab Override settings are not being saved when New Tab Override "Options" tab is closed, causing the new tab to be made to be blank rather than displaying the configuration that the user set. I think this can be fixed by adding a save button to save the configuration.

**Comment by cadeyrn** [comment]
There is no need for a save button, it should work. The add-ons has more than 130,000 users and there are zero other reports that the options are not being saved.

How do you verify that the options are not saved? If you change your settings, close the options tab and open the options tab again - do you see your changes or are the default values applied?

Please go to the Firefox preferences and open the panel "Home". There you can see which add-on controls your new tab page. Do you see a notice that your new tab page is controlled by New Tab Override? Or by another add-on?

It should look like the following screenshot:

![bildschirmfoto 2018-06-30 um 09 06 02](https://user-images.githubusercontent.com/1100614/42122625-d766f562-7c44-11e8-96b4-077e7d65656a.png)

(It's a German Firefox but you should get the idea)

**Comment by Mario3264** [comment]
Restarting Firefox to update seems to fix the issue...

**Comment by cadeyrn** [comment]
Glad to hear it works now!
