### ISSUE TITLE
Focus is always on the page when the new tab opens

### ISSUE THREAD

**Issue by cjkent** [cadeyrn/newtaboverride#157]
I have a custom URL for my new tabs and I have unchecked the option "Set focus to the web page instead of the address bar". But the focus is still on the page.

**Comment by cadeyrn** [comment]
Seems to be another behaviour change of Firefox 61. I don't know if there is anything I can do but I will investigate which change in Firefox caused this. Maybe it's a bug in Firefox, maybe it's an intended change, we will see.

Thanks for reporting.

**Comment by tikky** [comment]
I have the same problem - Firefox 61.0.1 (64 bit) on Windows

**Comment by EMIQUART** [comment]
No se puede en Android

**Comment by cadeyrn** [comment]
@EMIQUART: Please write in English oder German, I don't speak any other language. And please don't hijack issues. I don't understand your comment, but I can read "Android" and this issue has nothing to do with Android.

Thank you.

**Comment by bbay** [comment]
same here +1

**Comment by wagesj45** [comment]
Seems to still be an issue in Firefox 64.0 (64-bit). Any information about what could be the problem, or if there is a workaround?

**Comment by cadeyrn** [comment]
caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1410591.

**Comment by cadeyrn** [comment]
It's not clear if this behaviour change is expected. I Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1516777.

**Comment by gburning** [comment]
@cadeyrn I read the thread on Bugzilla. Is there a possible work around or will this feature be deprecated?

**Comment by cadeyrn** [comment]
Unfortunately there is no workaround. The option will be removed with the next update of New Tab Override because I can't provide this option without platform support from Firefox.

**Comment by funnyflowerpot** [comment]
Just came to say I would also like to have this issue resolved. But judging from the Mozilla forums, the future looks grim. Thanks @cadeyrn for looking into this issue!

**Comment by cadeyrn** [comment]
The focus can be changed again in New Tab Override 15.0 (if you're using Firefox 80 or newer).
