### ISSUE TITLE
about:'blabla' als eigene url nicht möglich

### ISSUE THREAD

**Issue by Krudjan** [cadeyrn/newtaboverride#16]
aus z. B. about:superstart wird http://about:superstart – eine Seite die offensichtlich nicht existiert

**Comment by cadeyrn** [comment]
WebExtensions dürfen nur ganz bestimmte about:-Seiten als neuen Tab verwenden, die meisten nicht. Da kann ich leider nichts machen. Abgesehen davon gibt es ab Firefox 57 sowieso keine about:-Seiten bei Add-ons mehr.
