### ISSUE TITLE
Extension seems stuck in an infinite refresh loop (Firefox 61.0.1, Win10 x64)

### ISSUE THREAD

**Issue by al4** [cadeyrn/newtaboverride#160]
First of all thanks for providing this extension! I've found it very useful, just seem to have found a small bug. I am using version 14.0.2.

To reproduce:

1. Open browser
1. Browse to any website
1. Open a new tab

Extension is stuck constantly refreshing the page. CPU core pegged at 100%. Address bar is blanked after typing a single character, but the "magic autocomplete" bar is still there... so you can navigate to a page if it appears in search results for a single character 😄.

Workaround:

1. Open a new window instead

Not sure if it's relevant, but I also have uBlock Origin, Vimium, and NoScript installed.

**Comment by cadeyrn** [comment]
Hi,

could you please attach a screenshot of New Tab Override's settings?

Thank you.

**Comment by i22tha** [comment]
I am having the same issue. 
Version 14.0.2, Firefox 61.0.1, macOS High Sierra

![screen shot 2018-07-10 at 11 58 38-fullpage](https://user-images.githubusercontent.com/6672986/42503387-cea184d2-8438-11e8-9e45-c0bc33cce39d.png)

**Comment by cadeyrn** [comment]
about:blank is not a valid URL and about:blank can't be used in the tabs API of WebExtensions since Firefox 60. If you want an empty tab as new tab page you don't need this add-on at all. There is a visible setting in about:preferences#home.

**Comment by voxik** [comment]
I experience the same issues. Going to test the about:preferences#home tip. Thx

**Comment by voxik** [comment]
And remove the extension, sorry ;) It made its job.

**Comment by al4** [comment]
@cadeyrn thanks for responding so quickly. I was also using about:blank as the new page. I think I installed this extension when Mozilla introduced Firefox Home and removed the blank page option. It was very helpful at the time! But I just want a blank page on opening a new tab, so I guess I don't have a need for this extension any more. Apologies for the mis-directed bug report 😃

**Comment by cadeyrn** [comment]
Glad to hear that your problems are fixed! If it means that you no longer need New Tab Override this is no problem at all. I am happy if the reason for uninstalling my add-on is that it's no longer necessary. :)
