### ISSUE TITLE
page 'flashing'

### ISSUE THREAD

**Issue by PosterBurner** [cadeyrn/newtaboverride#161]
All worked fine, but suddenly when I open a new page it is like someone is refreshing and hitting escape over and over real fast. The new tab 'flashes' and the refresh/x button in the browser flashes...like high speed refresh requests? Almost like a key is stuck. I do not believe anything else has changed. No idea what started it.

**Comment by cadeyrn** [comment]
Check New Tab Override's settings. Only valid URLs are supported (about:blank is not a valid URL and there is no need to install an add-on at all if you want an empty new tab).

**Comment by PosterBurner** [comment]
OK, github is a mess to find anything. Going to 'insights' shows that this is a known issue, the plugin no longer works, you need to remove it, as an update to firefox made it useless. Of course, good luck figuring that out. Nobody wants to bother to tell anyone that. Bye.

**Comment by cadeyrn** [comment]
> Going to 'insights' shows that this is a known issue, the plugin no longer works, you need to remove it, as an update to firefox made it useless

That's not true at all! The add-on works without any problems for valid URLs. For empty tabs no add-on is needed, there is a visible option in Firefox!
