### ISSUE TITLE
Do not force http:// prefix with other valid URIs like data:

### ISSUE THREAD

**Issue by JobLeonard** [cadeyrn/newtaboverride#162]
I tried adding this:

    data:text/html, <body contenteditable style="font: 2rem/1.5 monospace;max-width:60rem;margin:0 auto;padding:4rem;color:white;background-color:black;">

(try it, it creates a mini-note-taking page)

NTO changes it to this, causing a loop:

    http://data:text/html, <body contenteditable style="font: 2rem/1.5 monospace;max-width:60rem;margin:0 auto;padding:4rem;color:white;background-color:black;">

**Comment by cadeyrn** [comment]
Hi,

that's not possible for technical reasons. WebExtensions are only allowed to open HTTPS or HTTP URLs.

You have to setup a local web server like XAMPP or MAMP, save the HTML as file and use the local URL as URL for the new tab page.
