### ISSUE TITLE
Empty new tab URL string breaks browser behavior

### ISSUE THREAD

**Issue by overlord624** [cadeyrn/newtaboverride#164]
This addon allows setting an empty string to the new tab URL configuration option. However, if an empty string is specified, any new tab seems to infinitely reload itself, which makes the URL bar unresponsive. Assigning "about:blank" as the URL works normally.

Addon version: 14.0.2
Firefox Version: 61.0.1

**Comment by cadeyrn** [comment]
An empty string is no valid URL and doesn't make any sense at all. Why should someone do this?

If you want an empty new tab page open the Firefox' preferences and change your new tab setting. There is no need for an add-on like New Tab Override.

**Comment by overlord624** [comment]
Because it's possible that a user enters one by error or out if ignorance and end up having to track down what's breaking their browser, which is a time consuming process.

**Comment by cadeyrn** [comment]
I will implement a change so that New Tab Override's settings will be opened as new tab page if the url field is blank

**Comment by cadeyrn** [comment]
New Tab Override 14.1.0 with a fix for this issue has been released. Thanks for the report.
