### ISSUE TITLE
I open a new tab & Google's displayed - so what's wrong with that?

### ISSUE THREAD

**Issue by ttabolt** [cadeyrn/newtaboverride#165]
I keep getting a message from newtaboverride that my default is changed.  Yes, I know...I used nto to change it to Goggle.  Why tell me this as if something's wrong?  Have I not installed it right?  Please respond.  I really don't like superfluous messages - it makes me think some nefarious crap's going on in the background.  ttabolt@gmail.com

**Comment by cadeyrn** [comment]
The only notification that the default has changed comes from Firefox not from New Tab Override. If you get it more than once please consult https://support.mozilla.org. There is nothing I can do, sorry.
