### ISSUE TITLE
Support Firefox mobile [Android]

### ISSUE THREAD

**Issue by kekukui** [cadeyrn/newtaboverride#166]
New tab settings are not applied on Android

**Comment by cadeyrn** [comment]
There is no need for an add-on in Firefox for Android to change the new tab page. So what exactly are you requesting?

**Comment by h3298** [comment]
**Change new tab background color.**  For example:

The following settings produce a blank/empty new tab page

General | Home | Panels | Top Sites | Hide 
General | Home | Panels | Bookmarks | Hide
General | Home | Panels | History | Hide

Also use for new tabs = disable
__________________________________________________________________________________________________________

What happens now:

- **SETTINGS**

![settings](https://user-images.githubusercontent.com/20834957/44207046-bfe53200-a129-11e8-8672-cd1ee77bf460.png)


- **RESULT**

![result](https://user-images.githubusercontent.com/20834957/44206909-55cc8d00-a129-11e8-9c35-606d9f123e9d.png)

**Comment by h3298** [comment]
> It shouldn't be possible to install this add-on on Android since I didn't set any compatibility flag for Android on addons.mozilla.org. But I can confirm that it's possible. It seems I have to report a bug. :-/

oops, sorry, my fault -- there is no bug in compatibility flags -- I copied the URL from desktop by typing on the keyboard.  I should have searched the Firefox Android repository.

> Anyway, there is no WebExtension API to override the new tab page in Firefox for Android. First Mozilla has to implement this API, otherwise I can't do anything, sorry.

Okay, no problem, thanks.  I guess Firefox Android needs to implement a dark theme / night mode.

**Comment by yozachar** [comment]
Hi, thanks for the add-on. Any change in the WebExtension API exposed by [Firefox mobile](https://hg.mozilla.org/mobile-browser/), yet? I see many new add-ons are supported.

**Comment by cadeyrn** [comment]
No, this type of add-on is not possible on Android.
