### ISSUE TITLE
Re-open last closed tab action opens a new tab instead if new tab was created between them

### ISSUE THREAD

**Issue by scscgit** [cadeyrn/newtaboverride#167]
Steps to reproduce:
1. Enable "Set focus to the web page instead of the address bar" in the settings
2. Close any tab
3. Open a new tab (overridden by the addon)
4. Press CTRL+SHIFT+T

Expected result:
Either immediately, or at least after few tries, re-opens the closed tab

Actual result:
All re-opened tabs are replaced by a default new tab, which redirects the user to the custom page again, creating another "last closed tab" entry. If the user tries to work around that by pressing CTRL+SHIFT+T **twice very fast**, it actually **erases** the "last closed tab" entry within browser's history, as there is no other way in Firefox to even trigger such action or look up the forgotten closed tabs (obviously, not even the history helps the user if they were opened a long time ago).

Workaround:
I figured out that the "Set focus to the web page instead of the address bar" setting doesn't work properly, because even when it's disabled, the page still gets focused. That means simply disabling this option will fix the issue! (There are just some new annoying mozilla issues, e.g. if you start typing into address bar while it's being loaded, it soon either prepends your text before the new custom URL, or it replaces it.)

**Comment by scscgit** [comment]
I unsuccessfully tried to solve the issue, because there is a call to `browser.tabs.remove(tabId);`, which needs to execute first before we get the tab reference by `browser.sessions.getRecentlyClosed({ maxResults: 1 })`, but it literally doesn't even get executed after the `browser.tabs.remove(tabId);` finishes (though mysteriously, any other code placed afterwards still works). When I placed it outside the promise, it worked properly, but deleted the previous tab entry that the user had closed instead. Maybe someone who knows Firefox API better will find a solution, so I'm leaving my commit here for reference purposes: https://github.com/scscgit/newtaboverride/commit/5b4bc471b517dabe8bfe40c9918a7b36588f24d1

There is still the important parallel hazard with a double CTRL+SHIFT+T press that's remaining though, maybe it's related to `browser.tabs.getCurrent` or something similar. Also when the example from my commit is implemented, the `browser.sessions.getRecentlyClosed({ maxResults: 1 })` may also return a wrong reference if the user is too fast (for now I handled it at least by a simple string check).

However, I've found a complete workaround that I added to the previous post. Still, that may get broken any time after another Firefox update.

**Comment by cadeyrn** [comment]
Hi,

thanks for reporting. I can confirm the issue. But I have to wait for a solution for #157. Because of a change in Firefox 61 the website gets *always* the focus, with "Set focus to the web page instead of the address bar" enabled and with the same setting disabled. It's not yet clear if this is an expected side effect of another change in Firefox or not, so I reported a bug to Mozilla. Either there will be a bugfix in Firefox, then I have to wait for the bugfix, or there will be no change in Firefox, then I have to remove the option from New Tab Override (which will also fix this issue).

**Comment by cadeyrn** [comment]
Option removed, should no longer be an issue.
