### ISSUE TITLE
Setting about:blank makes moz-extension: url flash up for half a second

### ISSUE THREAD

**Issue by stupidus89** [cadeyrn/newtaboverride#17]
I have set the newtab page to `about:blank`. However, when opening a new tab, a `moz-extension:` url (similar to the one of the preferences) is visible for about half a second and the page loading animation is playing on the new tab. This is very annoying, especially, if you start typing in a url before the new tab has finished loading, as the address bar resets once the "loading" of the new tab is finished. 
I am using the VimFX addon, so I can press `t` to open a new tab and immediately start typing an address. Previously this worked very well, but with this intermediate url, that the webextension version of newtaboverride is calling, my workflow is broken, i.e. I need to wait for like half a second between pressing `t` and typing an address.

**Comment by cadeyrn** [comment]
Half a second seems very long, it's noticeably shorter for me. However, there is nothing what I can do. I have to use the APIs Firefox provide.

**Comment by cadeyrn** [comment]
Maybe this will be solved once the address bar for new tabs can be cleared. It's not yet clear for me, we'll have to wait and see.
