### ISSUE TITLE
New Tab Override does not work with moz-extension:// URLs

### ISSUE THREAD

**Issue by josh-berry** [cadeyrn/newtaboverride#171]
I would like to be able to set my new-tab page to a URL provided by another extension. I've tried two approaches to doing this and both have failed in different strange ways:

1. Use a custom URL. This doesn't work because the ':' in 'moz-extension://' gets dropped, so Firefox thinks it's trying to load something from "http://moz-extension//...".
2. Set the Firefox homepage to the moz-extension:// URL, and configure New Tab Override to use the homepage. This doesn't work either--when I open a new tab, I just get the New Tab Override options page.

Note that in both of these cases, I never see an error message telling me what's wrong--New Tab Override just goes to the wrong URL.

From a cursory inspection of the code, I suspect (2) is happening because your `URI_REGEX` does not take into account protocols other than HTTP(S). To address (2), I suggest you do something like the following to parse and validate URLs instead:

```js
function isURLValid(url_text) {
    var url;

    try {
        url = new URL(url_text);
    } catch (e) { return false; }

    if (url.protocol === 'file') {
        // fail file URLs or whatever
    }

    return true;
}
```

For (1), it appears you're adding "http" in front of the URL to make it a valid URL, so again, using the above check instead of the URI regex to determine whether to try adding "http" should fix this problem.

**Comment by cadeyrn** [comment]
URI_REGEX does not take into account other protocols than HTTP(S) because WebExtensions don't support anything else as new tab page. There is nothing I can do.

**Comment by hellscyth142** [comment]
Please re-open the issue.
This firefox extension: https://addons.mozilla.org/en-CA/firefox/addon/bookmarked-speeddial/
also overrides the new tab page, and can set it to a mozzilla url. This extension should also be able to do that.

**Comment by cadeyrn** [comment]
That's not true at all. This add-on add an speed dial as new tab page. There is no option at all to set the new tab page to something different.

**Comment by josh-berry** [comment]
> URI_REGEX does not take into account other protocols than HTTP(S) because WebExtensions don't support anything else as new tab page. There is nothing I can do.

This is not true. You can programmatically redirect a tab to a moz-extension:// URL in the same manner you are using for HTTP/HTTPS. For example:

```js
browser.tabs.getCurrent()
    .then(t => browser.tabs.update(t.id, {url: "moz-extension://..."}))
    .then(console.log) // or whatever
```

In any case, New Tab Override should show a proper error message telling the user what's wrong rather than just going to the wrong URL.
