### ISSUE TITLE
bug: newtaboverride dose not do actual about blank

### ISSUE THREAD

**Issue by chanjala** [cadeyrn/newtaboverride#172]
please, if i use about blank use firefoxes buildin about blank and not your own if you cant implement it 100% (dark theme of firefox, all white, my sleepiness is gone, im not amused)

you can see in following video the difference

[2018-12-23 00-01-40.flv.zip](https://github.com/cadeyrn/newtaboverride/files/2705614/2018-12-23.00-01-40.flv.zip)

or using vimeo: https://vimeo.com/307900761 <iframe src="https://player.vimeo.com/video/307900761" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

also you can see i try to work around stuff using your color thing using #000000 (black) but its not working correctly eiter cause you dont clear the adress bar for me to search using it but just put something behind it what is even more anoying

**Comment by cadeyrn** [comment]
There is nothing I can do, sorry.

If you want that the built-in empty page for new tabs is dark with the dark theme enabled you have to ask Mozilla to implement this change.

You can use the background color option of New Tab Override but WebExtensions are not allowed to clear the address bar, that's a known WebExtension restriction.
