### ISSUE TITLE
New Tab override 13 works with Firefox ESR 60-60.6.1 ; ESR not on v 64 yet!

### ISSUE THREAD

**Issue by alannsandiego** [cadeyrn/newtaboverride#178]
New Tab override 13 works with Firefox ESR 60 - 60.6.1
But the present New Tab override extension works with ONLY version Firefox v 64 and newer? Why?
New Tab override 13 works please make it available again or update your newer version
to work with Firefox ESR 60 and newer. Firefox ESR not on version 64 yet.

**Comment by alannsandiego** [comment]
This is an enhancement request

**Comment by cadeyrn** [comment]
Thanks for your interest on New Tab Override.

There were no new features in New Tab Override 14 which are needed in Firefox ESR 60. And there were changes in newer Firefox versions which required changes in New Tab Override. To keep the code simple new versions of New Tab Override focus on new Firefox releases. As you said New Tab Override 13 works in Firefox ESR 60.

**Comment by alannsandiego** [comment]
Yes well I can not download your version 13? that is the point.
Eventually ESR will get to v64?


Alan H. Robinson Jr.
alannsandiego@hotmail.com
-----------------------------------------------------------------------------------
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the
intended recipient(s) and may contain information protected from disclosure by applicable laws and
regulations.  If you are not an intended recipient, you may not review, use, copy, disclose or distribute
this message or any of the information contained in this message to anyone. If you are not the intended
recipient, please contact the sender by reply e-mail and destroy all copies of this message and any
attachments. Unintended transmission shall not constitute waiver of any applicable legal protection
afforded to this e-mail and any attached documents.

________________________________

**Comment by cadeyrn** [comment]
> Yes well I can not download your version 13? that is the point.

You can find all versions here:
https://addons.mozilla.org/de/firefox/addon/new-tab-override/versions/

> Eventually ESR will get to v64?

The next major release for Firefox ESR will be Firefox 68.

**Comment by alannsandiego** [comment]
okay thanks.


Alan H. Robinson Jr.
alannsandiego@hotmail.com
-----------------------------------------------------------------------------------
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the
intended recipient(s) and may contain information protected from disclosure by applicable laws and
regulations.  If you are not an intended recipient, you may not review, use, copy, disclose or distribute
this message or any of the information contained in this message to anyone. If you are not the intended
recipient, please contact the sender by reply e-mail and destroy all copies of this message and any
attachments. Unintended transmission shall not constitute waiver of any applicable legal protection
afforded to this e-mail and any attached documents.

________________________________
