### ISSUE TITLE
Move tabs below the address & navigation bar

### ISSUE THREAD

**Issue by PissedFirefoxUser** [cadeyrn/newtaboverride#179]
Hi, please provide an option to select placing my tabs below the address and navigation bar in Firefox 66.0.3 running in Windows 7 Professional, 32-bit. Apparently, the only way to do it now is to perform very complex edits and maneuvers with the userChrome.css file that I am not up to, since for sure I will screw something up. Thank you!

**Comment by cadeyrn** [comment]
Hi,

this request has nothing to do with New Tab Override which replaces the new tab page of Firefox. As you noted you can achieve this with a userChrome.css file - and that's the only possibility. WebExtensions are not to able to implement such a change.
