### ISSUE TITLE
redirect is not working 

### ISSUE THREAD

**Issue by DougJuggler** [cadeyrn/newtaboverride#18]
when I open a tab i get this. 
http://search.searchutilities.co/?uid=47923169-95aa-42d2-bcae-6f3c32189af5&uc=20170815&ap=appfocus183&source=en-dbpage-bb8&page=newtab&implementation_id=brandedtab_4.0.13

I have it set for firefox home page.  about:home

**Comment by cadeyrn** [comment]
I assume to get the same new tab page without New Tab Override, right?

Check your system for malware or other add-ons which are overriding the new tab page. It cannot be guaranteed that New Tab Override wins against other add-ons or malware.

**Comment by DougJuggler** [comment]
yes that was the reason I instaled over ride, I have done a few malwre checks with Iobit and Avg. I have looked online on how to remove this spacificly but none of the information that is provided works I have re installed windows even . I f i ever find out who wrote this virus I will cut that fukrs throat.
  I am hoping to find out how to set my pc back to normal

**Comment by cadeyrn** [comment]
Add-ons like New Tab Override are not able to solve this kind of problems, they only work on working Firefoxes. So I fear that you have to solve your problem in another way, sorry.

**Comment by DougJuggler** [comment]
thanks for nothing
