### ISSUE TITLE
New Tab Override ignores meta charset declaration in local file

### ISSUE THREAD

**Issue by carlf66** [cadeyrn/newtaboverride#180]
I have a local file with the declaration:
`<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">`
but in a new tab all the special characters are displayed as unknown. If the local file is loaded directly the characters are displayed correctly.  If the file is placed on the web and used as a nw tab override the characters are displayed correctly.

**Comment by cadeyrn** [comment]
What is the use case for using ISO-8859-1?

Unfortunately there is nothing I can do. I can detect the charset in the saved file but it's not possible to set the charset at runtime because the browser has to know the charset before JavaScript is executed.
