### ISSUE TITLE
Pop up disappears before able to act on it.

### ISSUE THREAD

**Issue by GitHubRandy** [cadeyrn/newtaboverride#181]
This just started, wasn't there before.  Windows 10.  The first time I open a new tab (happens only rarely after that), a pop up warning appears in the upper right of the screen.  Something about New Tab Override changing a page.  There are two buttons to click on, but the pop up disappears before it can be read, or any action taken.  VERY ANNOYING!  What can be done to disable it?  Thanks.

**Comment by cadeyrn** [comment]
This dialog comes from Firefox. There you can report bugs in Firefox:
https://bugzilla.mozilla.org/
