### ISSUE TITLE
Not working in firefox 67 while in private browsing mode

### ISSUE THREAD

**Issue by ANewDawn** [cadeyrn/newtaboverride#182]
Each time firefox is started when i go to open new tab it brings up firefox's default private browsing page instead of my homepage.

I noticed if i disable and enable the extension then it works so long as firefox is open. Once firefox is closed and opened again it reverts back to firefox default new private browsing page.

If you have time to look into this issue be much appreciated. If you need any other info let me know.

Many thanks

**Comment by ANewDawn** [comment]
It appears add-on flagfox was the issue. Disabling the add-on made new tab work again.

**Comment by cadeyrn** [comment]
Hi,

thanks for letting me know. Maybe you can report the problem to the developer of flagfox? Thank you!
