### ISSUE TITLE
Open bookmark manager in new tab

### ISSUE THREAD

**Issue by Gz75y45ms3kc** [cadeyrn/newtaboverride#183]
I have set my home page as chrome://browser/content/places/places.xul and would like to use this extension to also set it as the URL for new tabs. When I try to configure this, the page instead loads https://chrome//browser/content/places/places.xul

**Comment by cadeyrn** [comment]
WebExtension can't open chrome:// URIs as new tab page.

**Comment by BeatLink** [comment]
Is there an upstream issue requesting implementation of this feature that we could track?

**Comment by fuesec** [comment]
same question as @BeatLink

**Comment by cadeyrn** [comment]
This won't ever be allowed for security reasons.
