### ISSUE TITLE
Flagfox extension stops NTO

### ISSUE THREAD

**Issue by Bobuntoo** [cadeyrn/newtaboverride#185]
I had a problem with NTO, until today!
NTO is set to open my current home page, but after I quit, then reopen FF, new tabs would give me the Firefox Private Browsing page. 
When I disable and re-enable NTO, I would get my home page again in new tabs, but only for the current session.
Reading that it might be an issue with my Firefox profile, I finally 'refresh'ed FF to default settings.  When I started reinstalling the usual Firefox extensions, I restarted Firefox after each one was installed. All went well, till the final one, being Flagfox, went in. Then the problem was back!
Since removing Flagfox, NTO has been fine. (I didn't try simply disabling the Flagfox extension.)

I thought people might like to know this!
Is this the best place for such a post? or is there a forum for NTO family members? Because I have other things to share!

**Comment by cadeyrn** [comment]
Thanks for the report. There were already other issues about the Flagfox problem. You should report this problem to the Flagfox developer. I'll close this one as duplicate.

> Is this the best place for such a post? or is there a forum for NTO family members? Because I have other things to share!

Yes, this issue tracker is the right place for bug reports and feature requests.
