### ISSUE TITLE
Possible bug when attempting to re-open previously closed tabs

### ISSUE THREAD

**Issue by mkirisame** [cadeyrn/newtaboverride#186]
Sören, you very likely know the key combo CTRL+SHIFT+T to re-open a previously closed tab.

Noticed it fails sometimes and all I can open is the new tab page.

![981264](https://user-images.githubusercontent.com/37766263/64410890-4d285b00-d08c-11e9-8816-c8a4fb2b47bc.png)

1) I was surfing youtube and then started a google search by creating a new tab
2) closed the youtube tab
3) used CTRL+SHIFT+T
4) It didn't open the youtube tab but moz-extension://..../newtab/...

Thus no matter how often I used CTRL+SHIFT+T, i could never access the closed youtube tab due to the dormant moz-extension tab spawning new google tabs.

**Comment by cadeyrn** [comment]
I cannot reproduce the probleme. Do you have other steps to reproduce? Which version of Firefox and New Tab Override do you use? Does the problem also exists with only New Tab Override and no other add-on installed?
