### ISSUE TITLE
Feature Request: Option to set the typing focus to adressbar after openen a new tab

### ISSUE THREAD

**Issue by WinMinerGMX** [cadeyrn/newtaboverride#187]
I wonder if it would be possible / easy to add a user selectable option to set the typing focus to the address bar, so when you open a new tab and want to change to a differen URL you don't have to click into the addressbar before typing.

**Comment by cadeyrn** [comment]
Unfortunately there is no WebExtension API to do this. :-(

**Comment by WinMinerGMX** [comment]
Ah well I guess that's just too bad. Thank you for the insanely quick reply. :)

**Comment by hondacbr600** [comment]
I know it's closed, but I wanted to point out that "New Tab Tools" has the ability to do it and I wondered if something's changed maybe?

P.S. I have other issues with the "New Tab Tools" and decided to host such a page/thumbnail grid myself, the address bar not clearing is the only issue with this approach.

**Comment by cadeyrn** [comment]
As far as I can see New Tab Tools does not allow to set a website as new tab page at all.

**Comment by hondacbr600** [comment]
Yeah, but the address bar is blank and on focus.

![image](https://user-images.githubusercontent.com/15723130/209461097-ce27c7e8-0e5b-4e3e-932e-0cafda30f9b1.png)

![image](https://user-images.githubusercontent.com/15723130/209461159-f4f5f50d-c45a-42fa-9e57-8298ef110721.png)

**Comment by cadeyrn** [comment]
The implementation of a static page as new tab page is something completely different as the impementation of a user chosen website as new tab page. Both work in a different way.
