### ISSUE TITLE
Keystroke assignment should be optional

### ISSUE THREAD

**Issue by rakoczy** [cadeyrn/newtaboverride#188]
It seems that ANY arbitrary keystroke assignment in an extension may lead to a conflict. 
Thus always all keystroke assignments should be either optional or configurable. 
Unfortunately, there's no way to avoid grabbing SHIFT+F12 keystroke by the extension, despite the fact that description states "It is also possible to open the settings interface via entering newtab settings in the address bar or via the menu entry in the tools menu." 
While I understand that it could be to much of work to add a configurable keystroke I strongly suggest at least a "disable" option for it.

**Comment by cadeyrn** [comment]
> Thus always all keystroke assignments should be either optional or configurable.

The keystroke assignments of *all add-ons* are configurable in the add-ons manager of Firefox. That's a feature of Firefox itself.

<img width="452" alt="Bildschirmfoto 2019-10-06 um 14 11 04" src="https://user-images.githubusercontent.com/1100614/66268973-2738d680-e843-11e9-9104-280bada51a58.png">

The screenshot is in German. But it's the last entry in this menu in every language.
