### ISSUE TITLE
Settings - Options - Home Page

### ISSUE THREAD

**Issue by 011V32** [cadeyrn/newtaboverride#19]
Hello,

it would be great if you could choose the configured home page of firefox preference tab.
In german "Startseite".
Thx.

Regards.

**Comment by cadeyrn** [comment]
It will be possible in future versions of Firefox (Firefox 57 at the earliest) but is not possible in Firefox and Firefox 56.

**Comment by cadeyrn** [comment]
It will be possible in Firefox 57 and will be implemented as a new option in a future update of New Tab Override. It's not yet clear when an update with this feature will be available, but it's clear that Firefox 57 is a strict requirement, it won't work with older versions of Firefox.

**Comment by cadeyrn** [comment]
Mozilla did not implemented this feature as requested by me, so I can't provide this feature.

**Comment by cadeyrn** [comment]
New hope for Firefox 57:
https://bugzilla.mozilla.org/show_bug.cgi?id=1397081

**Comment by cadeyrn** [comment]
It's implemented in the current development version, will be part of the next update of New Tab Override and will require Firefox 57. The update will also be released for users of Firefox 55 and Firefox 56, but only users of Firefox 57 and higher are able to use the new option.

**Comment by cadeyrn** [comment]
It's part of New Tab Override 9.0, released a few minutes ago.
