### ISSUE TITLE
Deprecated function found according to developer.mozilla.org

### ISSUE THREAD

**Issue by DoubleTheP** [cadeyrn/newtaboverride#193]
While reading some of your code, I discovered in file "src/js/core/background.js" line 95, that `browser.extension.getURL` is deprecated according to [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getURL). Still, I haven't noticed any problems while running the add-on.

**Comment by cadeyrn** [comment]
Thanks for the notice. I will replace the deprecated method call in the next update. :)
