### ISSUE TITLE
prepends http:// to moz-extension://

### ISSUE THREAD

**Issue by tomowad** [cadeyrn/newtaboverride#194]
I'm trying to make new tabs open with my OneTab page, which uses the moz-extension:// scheme. When I save, New Tab Override prepends http://

The same url works correctly as my default page for new windows.

**Comment by cadeyrn** [comment]
It is not possible at all to use moz-extension:// URIs as new tab pages.

**Comment by tomowad** [comment]
For anybody looking to do similar, a workaround I found was to set the moz-extension:// URI as the home page and to use the 'My Homepage' plugin to open new tabs with the homepage. (Although the page loads too slowly, so I'm not using it, unfortunately.)
