### ISSUE TITLE
User approval doesn't stick

### ISSUE THREAD

**Issue by ineuw** [cadeyrn/newtaboverride#198]
The add-on was installed by sync and I set it up as I needed (current home page) and gave my permission. But I must re-issue permission several times in the same session.

**Comment by cadeyrn** [comment]
The permission system is part of Firefox. There is nothing I can do. Please report a bug at https://bugzilla.mozilla.org for problems with Firefox. Thanks!

**Comment by ineuw** [comment]
Thanks for the info.
