### ISSUE TITLE
Don't spam history

### ISSUE THREAD

**Issue by splewako** [cadeyrn/newtaboverride#20]
With the version 7.1.0 and Firefox 56.0b2 under OS X I see visit with URL moz-extension://4005c95f-fea9-9648-b5db-b57de571ef4e/html/newtab.html (and no title) added to history.

Probably that URL also briefly blinks in address bar during new tab.

**Comment by cadeyrn** [comment]
Thank you for the report!

At the moment there is nothing what I can do. I'll file a feature request on the Mozilla bugtracker in the hope they will add a way to prevent the history spamming.

**Comment by cadeyrn** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1392063

**Comment by cadeyrn** [comment]
I'll implement a workaround which works with the "focus on the website" option enabled. It doesn't work with the default "focus on the address bar" behaviour, but it's better than nothing, I guess.

**Comment by cadeyrn** [comment]
I found a workaround to make it also work with the default behaviour!

**Comment by cadeyrn** [comment]
It's part of New Tab Override 9.0, released a few minutes ago.

**Comment by splewako** [comment]
Doesn't seem to work with 57b3, essentially like reported - urlbar blinks and moz-extension link is added to history.

**Comment by cadeyrn** [comment]
The title of this ticket is "Don't spam history" and this was fixed in New Tab Override 9.0. I tested ago a few moments ago with Firefox Nightly and it worked, no moz-extension URI was added to the history.

"that URL also briefly blinks in address bar during new tab" can't be fixed.

**Comment by splewako** [comment]
Ahhh, 58? I don't think I have enough patients to wait another moths for this but thanks anyway.

**Comment by cadeyrn** [comment]
It should work in Firefox 56 and Firefox 57, too. But I don't have access to other version than Firefox Nightly today.
