### ISSUE TITLE
Status on the address bar issue?

### ISSUE THREAD

**Issue by iwconfig** [cadeyrn/newtaboverride#201]
I was just trying out [this extension](https://addons.mozilla.org/firefox/addon/tab-master-5000) when I noticed it does not have the issue with the address bar. When I open a new tab and the custom tab extension is fully loaded, the native address bar is clear and active, ready for input.

Have you seen this? How is this possible? Is this an ugly "hack" or is this due to some recent changes from Mozilla? Maybe this is something New Tab Override can do too? Maybe not for custom URL's, but at least when only a background color is set.

**Comment by cadeyrn** [comment]
This is only possible if the user can't configure the URL of the new tab page at all, so it's not possible for New Tab Override.
