### ISSUE TITLE
New Tab Override with Windows 7

### ISSUE THREAD

**Issue by ScalaAccaZero** [cadeyrn/newtaboverride#202]
With:
Computer:
Operating system: Windows 7 Professional, service pack 1
Processor: Intel Core i3-6100 @ 3.70 GHz
Installed memory 16 GB

Firefox 75.0 (x64 it), updated

New Tab Override:
English (by Google Translator; when a voice is marked, I write a note):
Automatic update
Default Active Disabled (the first is activated)
Operation in anonymous windows
Allow Don't allow (the first is activated)
If permission is granted, the extension will be able to access your online activities in anonymous windows. Further information
Author
Sören Hentzschel
Version
14.4.0
Last update
April 10, 2020

Italian text:
Aggiornamento automatico
Predefinito Attivo Disattivato : il primo è attivo, gli altri due no
Funzionamento in finestre anonime
Consenti Non consentire : il primo è attivo
Se viene garantito il permesso, l’estensione potrà accedere alle tue attività online nelle finestre anonime. Ulteriori informazioni
Autore
Sören Hentzschel
Versione
14.4.0
Ultimo aggiornamento
10 aprile 2020

When asked, I authorized
As antivirus I have:
- Avira 15.0.2004.1828
- CCleaner 5.62

In Firefox 
Firefox è attualmente il browser predefinito= Firefox is currently the default browser
in "Firefox Home page and new windows"  I set https://www.google.it/
In the configuration of New Tab Override (short: NTO) 
I have alwais pagina iniziale attuale=current home page
I switch to URL personalizzato= Custom URL, I set https://www.google.it/
I don't know how to save the setup (here I think that it is the problem);
I tryed to save the setup in different way but I did'nt suxceed in saving,
so it's enought to exit from Firefox and to enter again and everything goes as if I did'nt configure NTO
Sorry for my simple english; for more info, here I am, obviously very tight in the house

ScalaAccaZero from Bologna, Italy

**Comment by cadeyrn** [comment]
> I don't know how to save the setup

There is no need to press a save button, all changes are applied immediately.

If it doesn't work then you have a problem on your system. Maybe it's the CCleaner (Really, you should never allow tools like CCleaner to do anything on Firefox, never!). On a clean system New Tab Override works with Firefox 75, I verified this a few moments ago.
