### ISSUE TITLE
[FEATURE REQUEST] Custom URL in New Tab

### ISSUE THREAD

**Issue by gaveitatry02** [cadeyrn/newtaboverride#203]
Hi.  I'd like to change my New Tab URL to:
chrome://browser/content/places/bookmarksSidebar.xhtml

but your extension changes it to
http://chrome://browser/content/places/bookmarksSidebar.xhtml

which breaks it and prevents it from working.

Can you make an exception for this particular URL (or ones like it i.e. chrome://), please?

**Comment by cadeyrn** [comment]
Hi,

this is technically not possible.
