### ISSUE TITLE
local file can't use background image

### ISSUE THREAD

**Issue by ErnieFR** [cadeyrn/newtaboverride#206]
Firefox latest version 76.0.1 (64-bits) still making it SO HARD to simply repeat the opening startpage for every new tab opened (what is the bloody problem with that?) but NewTabOveride is not so easy too.
If I select 'use startpage' it uses the Override Settings page as startingpage for new tabs BOOHOO. 
Then I select 'use local page' and it will permit me to select my homemade favorite URL-links-page, but refuses to look at the linked background image file in the same directory and produces therefor a crappy page. How hard can it be folks?

**Comment by cadeyrn** [comment]
Unfortunately there are many restrictions with the local file approach. It's more a workaround to get some use cases working at least. If you want to use a local file without any restrictions you have to setup a local server. It's not difficult at all with a tool like XAMPP or MAMP and works like a charm with the custom URL option.

**Comment by gamer191** [comment]
Possible workaround, which imo is easier than setting up a local server:
1. navigate to `%APPDATA%\Mozilla\Firefox\Profiles` (probably a different location on MacOS and Linux)
2. open your profile, followed by `extensions`. Then open `newtaboverride@agenedia.com.xpi` in 7zip or another archive manager and navigate to the `html` folder. This is the folder where the new tab file gets opened from
3. copy your image file into that folder. Your HTML file will be able to open it using relative links

@cadeyrn would it be possible for newtaboverride to create a folder in `Profiles\PROFILE\browser-extension-data`? That way the image could just be symlinked

**Comment by cadeyrn** [comment]
Your workaround is neither easier nor possible without disabled signatures verification and therefore not be recommended for security reasons.

**Comment by cadeyrn** [comment]
Your workaround is not significantly easier than starting a local server. Once installed, you only have to press a button to start it. It can also be configured to auto-start, of course.

Also I am not sure whether your workaround will work at all if you don't disable the signature verification. This is something that no one should do for security reasons.

**Comment by gamer191** [comment]
> Also I am not sure whether your workaround will work at all if you don't disable the signature verification

Sorry, I was just about to come back to mention that. I totally forgot that I had disabled signature verification (something only possible on Firefox ESR, Developer Edition, and Nightly

So you're correct that it's not possible for the average user

> This is something that no one should do for security reasons

I don't agree tbh.
Off topic rant: unless someone is unfamiliar with security and decides to install extensions from random websites, I honestly can't see any issue with disabling extension signature verification. Sure a program with access to your computer can modify your extensions, but it could also just copy all your sensitive information, such as your cookies and your saved passwords (both of which are stored in your appdata folder and easily accessible without an admin password)


Don't bother putting any effort into my above feature request, because I realised Tabliss is better for my usecase. Thanks heaps for this extension though!

**Comment by cadeyrn** [comment]
> unless someone is unfamiliar with security and decides to install extensions from random websites, I honestly can't see any issue with disabling extension signature verification. 

Even for someone who is familar with security, it is not realistic to guarantee the integrity of the files if you disable the signature verification. So this is an important security measure. It's not related to the download source at all.

**Comment by gamer191** [comment]
> Even for someone who is familar with security, it is not realistic to guarantee the integrity of the files if you disable the signature verification. So this is an important security measure. It's not related to the download source at all.

If you download extensions from a secure website (such as Github or Mozilla's addon store, with https-only mode enabled) the files won't realistically be tampered with, will they?

**Comment by cadeyrn** [comment]
The signature verification is not a security measure for the download, is intended to ensure the integrity of the data. The files could be changed at any time on your system. And the signature makes sure that modified add-ons can't run.
