### ISSUE TITLE
[Feature request] Cache webpage do not load it every time

### ISSUE THREAD

**Issue by aaronrancsik** [cadeyrn/newtaboverride#208]
Hello, 
First of all thanks for the nice work. 
I have a feature request. 
Please cache the selected webpage and do not load it every time it would be a much smoother experience. 
When I click to new tab it always load it and for a searx instance  it takes a while like 0.3 sec and it is annoying.
Thanks again!

**Comment by cadeyrn** [comment]
Duplicate of #145.
