### ISSUE TITLE
this addon should leave cursor focus inside URL bar

### ISSUE THREAD

**Issue by scottstensland** [cadeyrn/newtaboverride#209]
for years a very frequent action is to copy some text or url then wish to paste this into a new tab URL bar
problem with using this addon is it fails to leave the cursor focus in the browser URL bar so instead of

desired behaviour
ctrl t to open new tab ...  paste ... hit enter

wonky behaviour with this addon
ctrl t to open new tab ... click URL bar ... paste ... hit enter

Please put cursor focus into the browser URL bar upon opening up a new tab

**Comment by cadeyrn** [comment]
There is nothing I, as add-on developer, can do. This is how the WebExtenion API work.

**Comment by ylor** [comment]
So it looks like Firefox 80 resolved this for OP, but broke my behavior. New tab pages now focus the address bar even though I use the autofocus on my new tab page.

@cadeyrn do you have an option to allow the new tab to respect autofocus on load?

**Comment by cadeyrn** [comment]
I am not aware of any new API so it seems another behaviour change of Firefox and I don't think that I will be able to change anything. But to be sure I have to find out what exactly changed in Firefox. Unfortunately the tool mozregression is broken on macOS Big Sur Beta at the moment so I have to wait a bit until I can investigate.

**Comment by ylor** [comment]
Thanks for the fast response!

If it helps you should be able to at least be able to observe the behavior by installing current Beta, Dev, or Nightly. Set URL to DuckDuckGo and observe how focus remains in the address bar when it should be in the search box.

There may be more but from a cursory search it appears appears to be related to the following issues in Bugzilla:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1596738
* https://bugzilla.mozilla.org/show_bug.cgi?id=1643578
* https://bugzilla.mozilla.org/show_bug.cgi?id=1651919
* https://bugzilla.mozilla.org/show_bug.cgi?id=1652165
* https://bugzilla.mozilla.org/show_bug.cgi?id=1653069

Hope that helps. Would you like me to open a new issue about this?

**Comment by ylor** [comment]
Good news! 

So just to see what would happen, I installed 14.2.0 on Nightly and checked the "Set focus to the web page instead of the address bar" checkbox just to see what would happen and it just works! 🙌

Again if you'd like me to create a new issue about this I'm happy to.

**Comment by cadeyrn** [comment]
Thank you for the investigation, that's very helpful! I will have a look on Monday. A new issue should not be needed since another user opened #211 a few hours ago.

**Comment by cadeyrn** [comment]
New Tab Override 15.0 was released and it includes a new (old) option to change the focus behaviour. Thanks again for your research, @ylor!
