### ISSUE TITLE
Can not set address from about:*

### ISSUE THREAD

**Issue by FeroxTL** [cadeyrn/newtaboverride#21]
I use extention superstart (https://addons.mozilla.org/ru/firefox/addon/super-start/) and it has address on new tab about:superstart. It has worked until today when newtaboverride got an update. So now when i set URL to newtabovveride about:superstart it converts it to http://about:superstart and superstart doesn't work - I see moz-extension://e5bf13e4-4edc-4321-b45a-fa550c389156/html/newtab.html instead of about:superstart

**Comment by cadeyrn** [comment]
WebExtensions are not allowed to use arbitrary about: pages as new tab page. Also, it's not possible that WebExtensions have an about: page so Super Start needs an update in any case, this URI won't exist in Firefox 57 and higher.
