### ISSUE TITLE
New Tab Override Extension doesn't move focus into window

### ISSUE THREAD

**Issue by CurveSurfer** [cadeyrn/newtaboverride#211]
Since the most recent update of Firefox (80.0b1) when I open a new tab I get the requested page, but the focus stays on the address line and doesn't move into the window. I have Google set up as my new tab page, and I expect the focus to move to the Google search line in the window like it always has. But now it doesn't do that, and I end up typing my search terms on the address line, which doesn't work (if searching on the address line is an option in Firefox, I have it turned off). Is it possible to persuade the add on to move the focus into the window like it has historically done ?

**Comment by cadeyrn** [comment]
There was a change in Firefox. I will have a look on Monday.

**Comment by cadeyrn** [comment]
I fixed the issue yesterday but since New Tab Override is a recommended add-on it means that every updates has to go through the manual review process and I don't know how long it takes to get the update published.

**Comment by cadeyrn** [comment]
New Tab Override 15.0 was released and it includes a new (old) option to change the focus behaviour.

**Comment by CurveSurfer** [comment]
Much better !!!  Thank you SO much !

**Comment by CurveSurfer** [comment]
I'm SAVED !!!

Thanks very much for the update ! Now it works like the good old days ....

Jim
