### ISSUE TITLE
Disable Focus on URL Bar

### ISSUE THREAD

**Issue by inthefold** [cadeyrn/newtaboverride#214]
Hi,

Since I updated Firefox D.E. from 78 to 80, every time I open a New Tab it automatically focuses on the URL Bar. I'd really like to disable this new feature, and get back to the old standard behavior... It would be great if it could be done through the extension.

All the best.

**Comment by cadeyrn** [comment]
New Tab Override 15.0 was released and provides a new option to set the focus to the website again.

**Comment by inthefold** [comment]
Yeah, I got the update shortly after posting, and it works like a charm. Thank you.
