### ISSUE TITLE
Blank new tabs option

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [cadeyrn/newtaboverride#215]
I want the option to open new tabs with a blank page as I could do before installing this add-on.
I'd uninstall it except I want the ability to choose where new tabs open, so I need it (or one like it).

I've been using [startpage](https://us.startpage.com/) as the new tab, but either it loads too slowly or I start typing too fast.

When I open a new tab, hit ⌘+L and start typing an address, it usually appends to the still-loading startpage address instead of typing a new address in a blank bar. So when I hit the Enter key, I end up with an error page.

Therefore I want a blank page so I can begin typing immediately.

**Comment by rogershijin** [comment]
I would also like this feature - currently [about:blank](url) doesn't appear to be a supported url.

**Comment by Lexicon9** [comment]
Seconded (thirded?), it would be _very_ nice

**Comment by thibnov** [comment]
fourthed ? 
it would be very useful

**Comment by cadeyrn** [comment]
An empty new tab page is an default option of Firefox. There is only one case for using New Tab Override if you want an empty new tab page, as mentioned by the issue opener: _"I want the ability to choose where new tabs open"_. Starting with Firefox 85 you will be able to disable the override of the new tab page with New Tab Override still enabled so you will be able to use this option together with the empty tab option of Firefox. Firefox 85 will be released in three weeks. Calling this feature request fixed.
