### ISSUE TITLE
Where is the option to set the focus to the page instead of the URL bar?

### ISSUE THREAD

**Issue by davidfstein** [cadeyrn/newtaboverride#216]
I can't seem to find this option anywhere in the settings

**Comment by cadeyrn** [comment]
It's in the settings of New Tab Override. You can find the settings in the add-on manager (in the three dots menu of the add-on) or you can use the toolbar button (if you didn't remove it) or you can use one of the other entry points:

> The settings interface can be accessed via Shift + F12. It is also possible to open the settings interface by entering newtab settings in the address bar or from the menu entry in the tools menu.

**Comment by davidfstein** [comment]
Whoops, I was on 79, just had to update to 80 and I see it now. Thanks
