### ISSUE TITLE
Cursor Position

### ISSUE THREAD

**Issue by Gummomarx** [cadeyrn/newtaboverride#218]
Since Firefox updated to 80.0, when I open a new tab (my home page = google.co.uk), the cursor lands at the URL bar instead of the Google search bar in the middle of the screen.

**Comment by cadeyrn** [comment]
Please make sure that you have New Tab Override 15 installed and that the option to set the focus to the website instead of the address bar is enabled.

**Comment by Gummomarx** [comment]
That's a perfect solution and - so fast!  Thank you very much.

**Comment by cadeyrn** [comment]
Glad that you're happy!
