### ISSUE TITLE
URL protocol type chrome:// on Mac OS does not work

### ISSUE THREAD

**Issue by The-Jag** [cadeyrn/newtaboverride#22]
Hi,

When moved to version FF 55.0.2 (64bit os x), New Tab Override changes to the extension version.

This version is not able anymore to handle an URL like this for new tabs, it only works for the very first tab when starting FF on Mac OS:

chrome://desktop/content/desktop.html

This type of URL is used with Desktop addon (https://addons.mozilla.org/de/firefox/addon/desktop/).

In the config dialogue of New Tab Override extension, the URL is wrongly completed with "http://" what ends up like this:

http://chrome://desktop/content/desktop.html

Of course FF tries to handle this URL and finds something like http://www.chrome.com//desktop/content/desktop.html, what is completely wrong (Google 404 page).

Tested on Mac OS Sierra 10.12.6.

On my Windows 10 installations with FF 55.0.2 (64bit), all of them version 1607, the chrome: protocol is handled correctly for new tabs.

**Comment by cadeyrn** [comment]
Please read one of the five hundred other tickets…
