### ISSUE TITLE
New tab focus issue

### ISSUE THREAD

**Issue by sanyi0411** [cadeyrn/newtaboverride#220]
Just today I noticed that when I open a new tab the focus moves to the address bar even though in the settings **Set focus to the web page instead of the address bar** in ticked. I tried undoing and redoing it, restarting Firefox, nothing helped. Last week wasn't an issue, the focus was on the webpage.

**Comment by SadSnowBear** [comment]
Hi,
Same here since a few days. New version issue? There was no problem before.
Please fix it.
Thanks in advance

**Comment by cadeyrn** [comment]
Make sure that New Tab Override 15.0 is installed and that the option to set the focus to the website instead of the address bar is enabled. If it doesn't help please show your configuration.

**Comment by sanyi0411** [comment]
I have removed and the re-added the extension to make sure it is the latest version. Then I disabled and enabled it from the Firefox Options. Now it is working properly. @SadSnowBear check if this process helps for you

**Comment by SadSnowBear** [comment]
Thanks a lot! Now is working here too :-)

**Comment by cadeyrn** [comment]
Great!
