### ISSUE TITLE
PLEASE add this add on to mobile!

### ISSUE THREAD

**Issue by HTSamurai** [cadeyrn/newtaboverride#222]
This add on is great, I use it on PC all the time. But I'd love to use it on my Android phone! Can you do this?

**Comment by HTSamurai** [comment]
This would be great!

**Comment by cadeyrn** [comment]
It's currently not possible.

**Comment by HTSamurai** [comment]
Why is it not? Just wondering

**Comment by cadeyrn** [comment]
There is no "new tab page" that can be replaced on Android. Also only selected add-ons are allowed on Android at the moment.

**Comment by HTSamurai** [comment]
Oh ok
