### ISSUE TITLE
Better visuals when focusing page by not waiting for the tab load

### ISSUE THREAD

**Issue by Juraj-Masiar** [cadeyrn/newtaboverride#225]
https://github.com/cadeyrn/newtaboverride/blob/5b8730b34b144af87aa779dada9f785fd6287892/src/js/core/newtab.js#L84
Hello,
I've noticed you are waiting for the tab to create before removing current one - this however causes the ugly effect when new full tab is added and then old one is removed. And if your tabs bar is full then all your tabs just shifts around... nasty!
But you can make it much better (almost perfect) by removing the tab right away:
```javascript
browser.tabs.create({ url : url, cookieStoreId : tab.cookieStoreId });
browser.tabs.remove(tabId);
```
The tab creation is started the moment you execute it so you don't have to worry about killing the origin tab right away!
I've been using this for years and it looks much better!

**Comment by cadeyrn** [comment]
Hi,

thank you very much for your suggestion. I will test this change within the next few days and apply your suggestion if I won't find any regressions. :)

**Comment by cadeyrn** [comment]
@Juraj-Masiar 

Sorry for the very long delay. I tested your change and was not able to notice any difference. Is this still an issue in Firefox 88? If you could you maybe make a small screencast to demonstrate the before/after change?

Thanks!

**Comment by Juraj-Masiar** [comment]
Yes it's still there. It depends how fast your PC is and how sensitive your eye is.
I'm not using this addon, I've noticed it when I was testing something and wanted to let you know.
But if no one else complains and you don't see it, I guess you can leave it as it is...
