### ISSUE TITLE
Cursor still won't automatically go to Google search box 

### ISSUE THREAD

**Issue by CoolBarn** [cadeyrn/newtaboverride#229]
Hi guys,

As the title says, every time I open a new tab (https://www.google.com.au/), the cursor never goes directly to the Google search box, even though I do have a tick in the box "Set focus to the web page instead of the address bar.  I have tried uninstalling/reinstalling the extension, taking the tick out and putting it back in, and opening up the new tab by both buttons and keyboard shortcuts.

No matter what I try, the cursor never automatically appears in the box like it used to a month or two ago.  If I start to type after opening a new tab, then the Quick Search text box opens up at the bottom of the page, and the page begins searching for what I am typing.  

I don't believe I have introduced any new extensions, and have had the same Firefox browser running for the past six months, simply updating it when offered.  But something has changed the way New Tab Override operates, so I'm hoping you can help me.  Thank you very much for your time  :)

**Comment by cadeyrn** [comment]
Hi,

what is your Firefox version and version of New Tab Override?

**Comment by CoolBarn** [comment]
Hi Soren,

Thank you so much for your quick response  🙂

My version of Firefox is 83.0 (64 Bit).

My version of New Tab Override is 15.0.0.

If I can give you any further information, please let me know.  Thank you so much for your help.

Regards,
Tony.


________________________________

**Comment by cadeyrn** [comment]
I cannot reproduce. Do you have other add-ons installed? Please check if the problem still exists if you disable all add-ons except New Tab Override.

**Comment by CoolBarn** [comment]
I have the following extensions installed, the problem still exists even when they are disabled:


[cid:e0e43dbd-d5a7-44bc-a625-e7e68612c0b0]

________________________________

**Comment by CoolBarn** [comment]
UPDATE : I refreshed Firefox, and the problem has fixed itself!  

That's a relief, thought I was going to have to start everything from scratch!  This has saved me an hour, which I can waste on other things  :D

**Comment by cadeyrn** [comment]
Glad that it works now! 😊

**Comment by CoolBarn** [comment]
Thank you very much for your prompt assistance mate, it is very much appreciated!

You are an excellent developer  🙂

Regards and take care,
Tony.

________________________________
