### ISSUE TITLE
about:mozilla as custom URL does not work anymore

### ISSUE THREAD

**Issue by TheUserToo** [cadeyrn/newtaboverride#23]
I configured in the settings to use a custom URL and as URL typed in about:mozilla.
This worked fine for Firefox 54.0.1 and the New Tab Override plugin version for it. After the update to Firefox 55.0.2 and the update of the New Tab Override plugin the about:mozilla is automatically rewritten to http://about:mozilla and if I open a new tab, I get a blank page and the URL moz-extension://6b642d45-7b21-4e22-87ee-fe6739652005/html/newtab.html in the address bar, but not the about:mozilla page.

**Comment by boy1dr** [comment]
Not sure if this is specifically the same issue but i just upgraded to version 55.02(64bit) from 54(32 bit) and now get "Access to local files is no longer possible for extensions" because my homepage is stored in my documents folder.
Looking for a fix :)

**Comment by MrPryor** [comment]
Having same problem here.

**Comment by cadeyrn** [comment]
Please read one of the five hundred other tickets…

**Comment by TheUserToo** [comment]
Why should I? I throw away your software and take a different one - one, that works. Have a nice rest-life.
