### ISSUE TITLE
Can't save setup

### ISSUE THREAD

**Issue by brittont0** [cadeyrn/newtaboverride#230]
When I have New Tab Override enabled, every new tab page opened with the "+" opens the New Tab Override settings page instead of a new home page.  I haven't figured out how to stop this, so have disabled the extension.  Firefox 83.0  New Tab Override 15.0.0

**Comment by cyrilcourtney** [comment]
Hello I am having the same kind issue today: anything I enter in the setup page is not memorized.

**Comment by Rexogamer** [comment]
> Hello I am having the same kind issue today: anything I enter in the setup page is not memorized (Firefox 83.0 - don't know how to retrieve extension version but up to date as of writing).

You should be able to get your addon version from the Firefox addon store?

**Comment by cadeyrn** [comment]
I am not able to reproduce. Maybe there was an issue in Firefox 83 that is already fixed? Please open a new issue if you can still reproduce. Thanks.
