### ISSUE TITLE
Reopening multiple tabs does not work. 

### ISSUE THREAD

**Issue by Rowanlikesdonuts** [cadeyrn/newtaboverride#232]
When you press ctrl+shift+t one time, it opens the last closesd tab wich is what's supposed to happen, but when doing it again, you just open the startpage (In my case duckduckgo).

**Comment by JamieRCHI** [comment]
I have Google as my start page in Firefox.
This happens for me whether I 'reopen' one tab or several.
I right click the tabs area and select 'Reopen Closed Tab' and this happens.

**Comment by cadeyrn** [comment]
I was not able to reproduce.
