### ISSUE TITLE
Request the possibility to continue using the about:newtab

### ISSUE THREAD

**Issue by SpinB** [cadeyrn/newtaboverride#233]
Hi, 
Can all the code be striped of the extension and make a new one that just as one option or can someone explain to me how can i make this the default behavior of Firefox.

**Set focus to the web page instead of the address bar **

Thanks.,

**Comment by cadeyrn** [comment]
If you want to use "about:newtab" as new tab page there is no point in using this add-on at all.

**Comment by SpinB** [comment]
I just want the option to **Set focus to the web page instead of the address bar ** from the extension, it would also be useful if the selection also applied when clicking toolbar icons, because i set my urlBar to expand when there's a focus on it, so every time i click the newtab button or click a toolbar icon that set focus on the urlbar, i get the urlbar expanded, so i would like to know or to remove this objects from setting focus on the urlbar.

**Comment by cadeyrn** [comment]
Add-ons can't do anything with "about:newtab", that's why New Tab Override requires a URL starting with https:// or http://. Even if I would like to handle a use case like this - it's not possible.
