### ISSUE TITLE
Feature Request: When focusing on address bar have entire address selected

### ISSUE THREAD

**Issue by hryanjones** [cadeyrn/newtaboverride#235]
it's very common for me to open a new tab and type a search or the beginning of an address I want. If the full address is selected then I can do this without skipping a beat, but without it I have to ctrl-a first before I can replace what's there.

Thanks for consideration!

**Comment by cadeyrn** [comment]
Hi,

thanks for the suggestion. I definitively would implement this behaviour if it would be possible - but it's not possible for WebExtensions.

**Comment by hryanjones** [comment]
le sad :(

Thanks for looking into this!
