### ISSUE TITLE
fails to work when firefox is re-opened

### ISSUE THREAD

**Issue by toobob** [cadeyrn/newtaboverride#236]
everytimr i close firefox or re-start pc, the enw tab override options clear and the extension fails to work. re-inputting all the options and waiting for several minutes causes the extension to work again.
also, the default surrent home page setting does not work - simply produces a blank page with cursor in address bar.
firefox 86

**Comment by cadeyrn** [comment]
This is clearly a problem on your system and does not correspond to the normal behavior of this or any other extension. Make sure that you don't have Firefox configured to forget all data when quitting and that you don't use tools like CCleaner or similar ones.
