### ISSUE TITLE
does not allow javascript to set input field, always selects URL line

### ISSUE THREAD

**Issue by johnea** [cadeyrn/newtaboverride#237]
Hello,
Thank you for the plugin. How sad that one is unable to simply set the new tab page in firefox.
My new tab page is set to the current homepage.
In my homepage, there is a search form. This form has javascript to set this field as the active input field when the page is loaded. However, since using NewTabOverride this javascript doesn't work. The javascript looks like this:
In html body statement: onLoad="document.forms.metasearch.search_input.focus()"
When I open a new tab, the current input is always in the URL line of the browser.
I also tried the html5 autoload="autoload" in the input field definition itself. This also didn't work.
Please help!

**Comment by cadeyrn** [comment]
Hello,

please mention the URL of the new tab page otherwise it's not possible to say anything about it. Thanks.

Btw, an "autoload" attribute for text input fields does not exist in HTML.

**Comment by johnea** [comment]
Thank you for your reply!
The URL: https://johnea.net
The cert is self signed, so you have to accept it to view the page.
Yes, I typed incorrectly, I was referring to autofocus.

**Comment by cadeyrn** [comment]
Sorry for the delay. It works for me - you have to enable the option in New Tab Override to set the focus to the website.

**Comment by johnea** [comment]
Thank you Sören.

However, I don't see this option. 

In the add-on's preferences page, I only see:

This page is provided by New Tab Override: Select which page should open as new tab!

Along with the ability to revoke the permissions.

Sorry if I'm missing something, but I don't see it here...

**Comment by cadeyrn** [comment]
Which version of New Tab Override do you use?

**Comment by johnea** [comment]
14.4.0

I enable updates, and when I check for updates it prints: No updates found

I attached an image of the settings page

**Comment by cadeyrn** [comment]
You need New Tab Override 15.0 or higher. New Tab Override 14.4 is the latest version that is offered on addons.mozilla.org at the moment. Version 15.0 is temporarily disabled and will be re-published as version 15.1 very soon (it's already submitted and is awaiting the review).

**Comment by cadeyrn** [comment]
@johnea New Tab Override 15.1 is available for download now.

**Comment by johnea** [comment]
Thanks for the update Sören!

However, it still doesn't seem to work for me. 8-(

After it didn't work, I restarted the browser, still no joy.

When I open the website:

https://johnea.net/

It leaves the text cursor focus on the URL line. If I create new tab, then start typing, the text goes at the beginning of the URL, not in the ixquick search text box, which should be selected by the page's javascript.

firefox just becomes more and more unusable. The mozilla foundation has abandoned the plugin makers repeatedly.

As I said before, just the fact that we need a plugin to set the page for a new tab, indicates they are trying to exert more control over the user interface experience.

If I'm going to run a browser crafted for the interests of goggle, I might as well run chromium.

I really appreciate your efforts with this plugin, and I will continue to use it, just to get the new tab page I desire, but it would really help if my cursor was in the place that the page's html and javascript dictate.

Thanks again for your help!

John

**Comment by cadeyrn** [comment]
> It leaves the text cursor focus on the URL line. If I create new tab, then start typing, the text goes at the beginning of the URL, not in the ixquick search text box, which should be selected by the page's javascript.

I cannot reproduce the issue, it works without any problems for me. As I already said in my first response you have to enable the website focus option that is available in NTO 15.

> firefox just becomes more and more unusable.

That's not true.

> The mozilla foundation has abandoned the plugin makers repeatedly.

This is not true either and I should know that since I am the developer of several Firefox add-ons, not only New Tab Override. And for the record, the Mozilla foundation is not involved in developing Firefox, that's the Mozilla corporation.

> As I said before, just the fact that we need a plugin to set the page for a new tab, indicates they are trying to exert more control over the user interface experience.

There are good reasons for that and I, even as developer of this add-on, fully agree with Mozilla's reasoning. And I know what I am talking about because I am not only a developer of Firefox add-ons, I am also the operator of the biggest Firefox forum in the German speaking countries so I know the issues from the past very well that led to this decision. It was an important and right decision.

> If I'm going to run a browser crafted for the interests of goggle, I might as well run chromium.

Well, now you're moving in the direction of trolling. Please don't do this.

**Comment by johnea** [comment]
Ah, I forgot the check box! Thank you!

Yes, it works now. Sorry for failing to enable.

This does help me continue to make use of this browser.

I'm glad you're happy as a plugin developer. 

While not a dev, I have been a user since netscape, and the user experience, for me, has demonstrated more and more interest in serving the organization, versus serving the users.

Tabs for some reason have often been at the center of this. Tab grouping, saving tab groupings, where all things firefox claimed would be supported, then internalize from plugins, then deprecated.

So, my experience has not been as positive as yours.

Don't mean to troll. Just expressing my frustration with mozilla, which is clearly not originating with you or your plugin.

Your work has made firefox continue to be usable for me.

Thank you...

John
