### ISSUE TITLE
Contents of URL bar are not selected

### ISSUE THREAD

**Issue by ScoreUnder** [cadeyrn/newtaboverride#24]
When opening a new tab, it's nice to be able to write a URL straight away without having to clear the URL already in the address bar. This extension doesn't select the URL, so you have to select or delete it manually. (I'm guessing this is a Firefox restriction, but I don't know for sure)

**Comment by cadeyrn** [comment]
As you can read in the addon's settings it's a current Firefox restriction. It will be possible again in the future but I have to wait, I can't do anything at the moment.

**Comment by earthbound19** [comment]
+1
