### ISSUE TITLE
Cannot set the default Firefox Blank page as new home page

### ISSUE THREAD

**Issue by Max1234-Ita** [cadeyrn/newtaboverride#240]
Hello,
I'd like to use the default firefox home page (blank page, with just a search bar, which is usually reached by typing "about:home" in the address bar:

![image](https://user-images.githubusercontent.com/15315381/114453393-c2013680-9bd9-11eb-9ee3-b3e0eb90563f.png)

Unfortunately theres' no option to set it: I tried specifying the address as a _custom URL_, but the extension treats it as a regular URL and makes it to become https://about:home; Other options? _Background color_... sets a custm color to a totally blank page and _local file_ loads a file from the local storage.

Can this be fixed, please?
Thanks in advance,
Max - Italy

**Comment by cadeyrn** [comment]
This is not possible for WebExtensions. Why do you need this option at all if it's a default option of Firefox?

**Comment by ShayBox** [comment]
Because the focus on the home page is the url bar and seemingly nothing can change that.
