### ISSUE TITLE
Feature Request: Allow empty address bar for custom URLs

### ISSUE THREAD

**Issue by Serenacula** [cadeyrn/newtaboverride#241]
Hi! Currently when we add a custom URL as a homepage, that site is added to the address bar. This looks messy for a newTab. I was wondering if an option could be added in settings, so that a newTab starts with an empty address bar even for a custom URL?

Similar to how a blank page has no URL.

**Comment by cadeyrn** [comment]
Hi,

this is not possible at all for WebExtensions.
