### ISSUE TITLE
NewTabOverride permissions issue in Firefox 88.0.1

### ISSUE THREAD

**Issue by ineuw** [cadeyrn/newtaboverride#244]
Firefox ignores the twice granted permissions to this add-on, resulting in a new tab opening to the add-on management page, instead of the home page.  Permission is granted the first time by tapping the permission bar in the add-on's management page, and then the 2nd time when opening a new tab. It still fails to properly register the permissions, and at times I must uninstall and reinstall to get it working for awhile.

**Comment by cadeyrn** [comment]
I cannot reproduce the problem. In general, if Firefox does not remember the permissions it's either a bug in Firefox (but then there would be a lot of support requests) or a problem in your device. Add-ons use permissions but they're not responsible for remember the permissions. So I suggest to open a support request on SUMO:

https://support.mozilla.org/en-US/

This can't be a bug of New Tab Override.
