### ISSUE TITLE
No option for Focus anymore. 

### ISSUE THREAD

**Issue by Elsie924** [cadeyrn/newtaboverride#246]
No option to focus new tab on search bar. 

Settings
Option
The web page entered here is displayed when opening a new tab. Only URLs starting with http:// or https:// are supported. Please note: Access to local files via URL is no longer possible due to Firefox restrictions. Please consider using the “local file” option or a local web server, for example via MAMP or XAMPP.
URL
Clear address bar / select URL
The automatic emptying of the address bar or selecting the URL is currently not possible for WebExtensions. This requires a change by Mozilla. Learn more

**Comment by cadeyrn** [comment]
The option to focus the website instead of the address bar is part of New Tab Override 15.0 and higher. New Tab Override 15.0 is currently disabled on addons.mozilla.org, New Tab Override 15.1 will be available very soon. It's awaiting the review by Mozilla.

**Comment by Elsie924** [comment]
Ahh. bummer. I have been unable to download previous version ie 14.4 instead
Any suggestion while waiting for 15.1?

________________________________

**Comment by cadeyrn** [comment]
There is nothing else you can do but wait. But I am pretty sure the new version will be approved within the next few days.

**Comment by Elsie924** [comment]
thank you. It has been killing me!!

________________________________
