### ISSUE TITLE
Focus on webpage

### ISSUE THREAD

**Issue by roanvanstaveren** [cadeyrn/newtaboverride#247]
Since yesterday i can't seem to set focus on the webpage which is opened. Has this feature been removed

**Comment by Gummomarx** [comment]
I had 15.0 installed but it reverted to 14.4 when I refreshed Firefox.

**Comment by cadeyrn** [comment]
To be clear: When you refreshed Firefox all add-ons were removed, not reverted to an older version. So you propably reinstalled the latest version from addons.mozilla.org and that's still 14.4 at the moment.

**Comment by Gummomarx** [comment]
When I refreshed, the add-ons re-instated automatically, almost certainly the latest versions came down from addons.mozilla.org rather than the versions I had active before the refresh.

**Comment by cadeyrn** [comment]
> When I refreshed, the add-ons re-instated automatically

I can't image that this really happened. This is not how the Firefox refresh works. Firefox even warns before the refresh that all add-ons will be **removed**, it's also documented in the Firefox help that this happens. In the Firefox support I've never heard something different. Reinstalling add-ons automatically would contradict the goal of the refresh.

Anyway, at this point it is only important that the new version of New Tab Override is still waiting for the review.

**Comment by Gummomarx** [comment]
I know and accept that Firefox warns as such so I decided to refresh again (for my own sanity) to discover that my add-ons DID automatically re-install.  I wonder if it's because I have a Firefox account - possibly my add-on list is saved?

Anyway, I have made a video of that refresh:
[https://gofile.io/d/escx0C](url)

**Comment by cadeyrn** [comment]
@roanvanstaveren @Gummomarx New Tab Override 15.1 is available for download now.

**Comment by Gummomarx** [comment]
Thanks you very much - that has made life much more easy.
