### ISSUE TITLE
How are you supposed to link .js files?

### ISSUE THREAD

**Issue by GitGondola** [cadeyrn/newtaboverride#248]
I have:
<script type="text/javascript" src="https://www.website.com/javascript.js"><br><br>

but get the log error:<br>
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

**Comment by cadeyrn** [comment]
You can't with the local file upload option. But if you run a local server (it's really easy and can be done in only a few minutes) then you can use your page with the regular website option.
