### ISSUE TITLE
Option to open blank page

### ISSUE THREAD

**Issue by oniony** [cadeyrn/newtaboverride#249]
I wanted to have new tabs open with a completely blank page. I tried putting 'about:blank' as the URL but the extension automatically adds a 'http://' prefix, changing the URL scheme from 'about' to 'http'.

1. An option in the drop-down for 'blank page' (which is actually about:blank).
2. Don't add 'http' scheme if the URL already has a scheme.

**Comment by cadeyrn** [comment]
This is neither possible for WebExtensions nor necessary. Just use the built-in option of Firefox if you wan to use a blank page as new tab page.
