### ISSUE TITLE
Opening a new background tab clears Location Bar

### ISSUE THREAD

**Issue by s4nji** [cadeyrn/newtaboverride#25]
**What Happens**
Opening a new tab in the background clears the location bar if [the feature is enabled](https://user-images.githubusercontent.com/1451155/29490311-087d5106-8528-11e7-99cd-ea0454d96ed8.png).

**Expected Behavior**
Location Bar should be cleared only if the new tab is opened in the foreground.

**Comment by cadeyrn** [comment]
Your screenshot shows the legacy version of New Tab Override. There will be no new updates for the legacy version. In fact it's not possible since the WebExtension is already released.
