### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by teeseus** [cadeyrn/newtaboverride#250]
is there a way to prevent this white-'Flash which happens on newTab?

**Comment by cadeyrn** [comment]
I don't know what you mean. Please provide detailled steps to reproduce.

**Comment by teeseus** [comment]
when one opens the newTab, before the extensions content appears, the newTab will be all white for a split second, flashing ones eyes

**Comment by cadeyrn** [comment]
Hi,

these are unfortunately not detailled steps to reproduce. What is your Firefox version? What is your version of New Tab Override? Do you use a light or dark theme? How did you configure New Tab Override? With the "extensions content" do you mean a website that you want to see as new tab page? If so which one?

**Comment by aptdamia** [comment]
The reporter is referring to the blank page that appears before the redirection to the custom url appears. 
The longer the custom url takes to load, the longer the user will see a blank page, which by default uses a white background.
IMO this might be similar to open it using browser.startup.page with option 0 (blank page).

**Comment by aptdamia** [comment]
I would say this is solvable (tested in my case) by changing the browser display background color:

Proposed solution:
1. Access about:config
2. search the preference called `browser.display.background_color`
3. Modify it to the preferred color using html color codes (e.g. black is #000000)
The default is white (#ffffff)

The change should be immediate and opening a new tab should show the new state.

To rollback the change, it is only required to search for the preference and select the reset option.

**Comment by aptdamia** [comment]
Note: Websites that don't specify the background color will be affected by this setting.

**Comment by nathanmp** [comment]
I'm having the same issue. From paying careful attention to the tab bar, it seems like a completely blank new tab (the background_color of the browser, like @aptdamia said) appears, then the new tab you set in the extension is created to the right of that, then the blank new tab disappears and you're left on the new tab you chose in the extension.
