### ISSUE TITLE
In Firefox for Ubuntu, the Home key opens a new tab instead

### ISSUE THREAD

**Issue by MykStreja** [cadeyrn/newtaboverride#254]
In Firefox for Ubuntu v92.0, when focused on a pinned tab, the Home key opens the home page in a new tab instead. I tested with settings on "use home key url" and "use custom url", and it works the same way. Running on an HP Stream 14, system information attached.

[HP Stream 14 - System information.txt](https://github.com/cadeyrn/newtaboverride/files/7267861/HP.Stream.14.-.System.information.txt)

Thank you.

**Comment by cadeyrn** [comment]
How is the home button related to this add-on?

**Comment by MykStreja** [comment]
I prolly forgot to say:
While the extension is active: If I try to go to my Home page using the
button while focused in a pinned tab, my home page instead opens up in a
new tab.
With the extension disabled, or in an unpinned tab, the Home button works
as expected.

It's not a problem for me since I can use the back button to return Home.
To make the point, it only affects pinned tabs. Your extension is exactly
what I needed, and I view this issue more as an undocumented feature than a
bug, but I thought you should be aware in case this dovetails with other
issues, and it might point up an issue with the code. Or I could be wrong.
YMMV

I fully intend to talk up this extension in the Ubuntu and Firefox forums I
visit. Thank you for your efforts.

Myk Streja

**Comment by cadeyrn** [comment]
I cannot confirm any difference in behaviour.
