### ISSUE TITLE
Bright light flash when extension is used in Firefox

### ISSUE THREAD

**Issue by AndyTelfer** [cadeyrn/newtaboverride#256]
Hi Sören, this is a very neat extension that I have been using on Firefox for several years now.

Lately, I have dark mode/theme enabled in Windows and in Firefox because I do a lot of work in the evenings in a dimly lit environment.

I am noticing that as Firefox calls the extension to open a new tab to my local html file, before my file is displayed there is a bright light screen/page that is displayed briefly before my dark html page is eventually displayed.

I think that I have traced this to the html/newtab.html default page that comes with the newtaboverride extension.

Is it possible that this default page could be modified on your side to follow either the user's system colour settings, or Firefox theme settings, or just make the background to this page be some dark colour?

I am guessing that the folks who have a light theme on their system and in their browser wouldn't mind if the page momentarily flashed dark before going to their light page.  But in my case the light bright flash is hard on the eyes.

Thanks for the extension and I appreciate any thoughts that you may have on this and what can be done, if anything.

**Comment by AndyTelfer** [comment]
I am sorry I can see that this problem was nothing to do with your wonderful extension.  It was caused by Firefox update 94.0

Thanks again for a great extension!

**Comment by Chillsmeit** [comment]
Have you found a fix for this? currently having the same issue in Firefox v.109.0
Super quick flash showing the default page before showing the custom url or background I set with the extension

**Comment by AndyTelfer** [comment]
Prior to v94 this is what I did to fix this:

about:config
browser.display.background_color
changed from:
#FFFFFF = white
to:
#191A1A = something dark
(#000000 = would be black)


This fixed it for me in v94:

1.In about:config make sure you still have a dark color defined for browser.display.background_color

2.Then (and this is the thing that changed in 94) go to Settings > Language and Appearance > Colors, set a dark background, and uncheck "Use system colors"


Good luck!
