### ISSUE TITLE
Select url on opening a new tab

### ISSUE THREAD

**Issue by harkairt** [cadeyrn/newtaboverride#258]
I got used to `cmd + t` and then type, then `enter`, but now with that I end up with:
```
<the thing I type>|<the url which I set to automatically load>
                  ^ cursor
```

If instead when opening a new tab `<the url which I set to automatically load>` is fully selected then I can just type my search term and it will replace the url instead.

**Comment by cadeyrn** [comment]
Hi,

unfortunately the behaviour can not be changed by add-ons.
