### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by LAZst** [cadeyrn/newtaboverride#26]
Hi!

Is it possible to remove automatic addition "http://" when using custom URL?
Because in my case I want to open "chrome://desktop/content/desktop.html" and 
naturally "http://chrome://desktop/content/desktop.html" don't work.

Thank you.

P.S. Firefox 55.0.2 (64-bit)
Addon 7.1.0 version

**Comment by cadeyrn** [comment]
No, it's not possible. Only HTTP, HTTPS and a very small subset of about: pages is allowed. See one of all the other closed tickets.
