### ISSUE TITLE
Select url bar text on new tab

### ISSUE THREAD

**Issue by designly1** [cadeyrn/newtaboverride#262]
Is it possible to call `browser.urlbar.focus( { select: true } )` after `browser.tabs.update()`?

I've been reading on Mozilla's developer site and I guess `urlbar` is a privileged API. It also requires the `urlbar` permission.

**Comment by cadeyrn** [comment]
Only Mozilla can use privileged WebExtension APIs. There is no way for regular WebExtensions to select the URL in the address bar.
