### ISSUE TITLE
Umlaute falsch dargestellt

### ISSUE THREAD

**Issue by TigraTT** [cadeyrn/newtaboverride#279]
in meiner lokalen Datei habe ich Umlaute die in Firefox richtig dargestellt werden, beim Aufruf über New Tab leider nicht.
Ebenso ist meine Datei im Browserfenster kleiner als wenn ich die Datei direkt aufrufe.
Die Datei ist eine Tabelle mit Links

in my local file I have umlauts which are displayed correctly when opening with Firefox, but unfortunately not when opening a new tab with New Tab enabled.
Also my file (a table with links) is smaller in the browser window than it is when I open the file directly with firefox.
In firefox directly it is full size of browser window and has no border, in New Tab it is smaller and ahs a white border.

**Comment by cadeyrn** [comment]
Hallo,

kannst du die Datei bitte hier anhängen, damit ich versuchen kann, das Problem zu reproduzieren? Du kannst die Datei vorher natürlich gerne soweit reduzieren / verändern, dass das Problem noch sichtbar ist, du aber nichts teilst, was du nicht teilen möchtest.

Danke!

**Comment by TigraTT** [comment]
das TXT am Ende wieder entfernen, dann sollte es passen.
ist nix besonderes, einfach nur ne Linksammlung.
[startsei.htm.TXT](https://github.com/cadeyrn/newtaboverride/files/9351417/startsei.htm.TXT)
?

**Comment by cadeyrn** [comment]
Es gibt bereits mit der Datei, so wie sie angehängt ist, ein Umlautproblem, wenn ich die Datei in Firefox öffne, also noch bevor New Tab Override involviert ist. Bitte stelle sicher, dass UTF-8 als Zeichensatz verwendet wird und Umlaute korrekt dargestellt werden. Wenn das der Fall ist, funktioniert das auch in New Tab Override.
