### ISSUE TITLE
Select all text in address bar on new tab

### ISSUE THREAD

**Issue by dangodai** [cadeyrn/newtaboverride#28]
When opening a new tab using custom URL, local file, or background colour, and having focus set the the address bar, the cursor is placed at the beginning of the address instead of selecting all of the text.

This means I now have to press ctrl+a before I can start typing an address. Before WebExtensions opening a new tab would select all the text in the address bar. I don't know if this is a possibility yet with WebExtensions. An alternative would be to just clear the address bar after setting the page, but again I don't know if this is possible yet.

**Comment by cadeyrn** [comment]
As you can read on the options page…

> Clear address bar
> The automatic emptying of the address bar will be possible again in later versions of Firefox. This requires a change by Mozilla.

**Comment by Arnaudv6** [comment]
I read the answer. Twice, for I read it in options too :-)
This title gave me an intuition though:
I can understand the security dilemma about extensions that would change the content of address-bar...
But would the extension SELECT all, it'd have the same effect as emptying the space:
when user types with his keyboard, everything else would go blank: Can this be done?
I can think of no security measure here ?

**Comment by cadeyrn** [comment]
I agree that there a less security implications if the URL will be selected instead of cleared but unfortunately that's also not possible. I still hope that this will be possible in the future.

**Comment by Arnaudv6** [comment]
Ok, thanks ! Is there a bug tracking this at mozilla's ?
