### ISSUE TITLE
Tab Stash

### ISSUE THREAD

**Issue by Dennismn** [cadeyrn/newtaboverride#281]
Hi, I use the add-on Tab Stash to organise my bookmarks. However when I insert its URL "moz-extension://058b06bc-3816-4628-9f6e-d5cea7590e31/stash-list.html" to your add-on New Tab Override, it gives me a server not loaded page. 

I'm wondering if it's possible to fix this. Thanks.

**Comment by cadeyrn** [comment]
Hi,

no, it's not possible to use use anything else than https:// or http:// for the new tab page.
