### ISSUE TITLE
Local file (used for New tab) does not have its JS executed

### ISSUE THREAD

**Issue by v-ko** [cadeyrn/newtaboverride#283]
I may've mislabeled the problem, but as much as I could understand - the file gets saved into the extension storage. Gets opened in a new tab. But the JS does not get executed. And I'm talking about JS that's embedded in the page, not some other local .js file. I'll attach the content of the html file I tested with:
```
<html>

<body>
    <div id="mapPage">

        <a href="https://www.facebook.com/groups/?ref=bookmarks">
            Facebook Groups
        </a>

    </div>

    <script>
        alert('test')
    </script>
</body>

</html>
```

I would expect the JS to work, since otherwise any dynamic content is broken. 

PS: Otherwise the addon is great, thanks for your work

**Comment by wetternest** [comment]
Same problem here. Has anyone found a solution?

**Comment by cadeyrn** [comment]
Please start a local server for complex local files, as explained in the extension. Then you don't have any restrictions at all.
