### ISSUE TITLE
Possible To Show New Content Just Below What Firefox Showing On New Tab

### ISSUE THREAD

**Issue by SalmaBegumJSR** [cadeyrn/newtaboverride#288]
Greetings, 
thanks for this nice addon

but i like what currently Firefox shows as new tab, (the most visited websites)

is there any way that your add a option to show custom url/page content just below/above what is currently Firefox showing as new tab content? please?

hope that make sense?

thanks in advance
best regards

**Comment by cadeyrn** [comment]
Hi,

this is not possible.
