### ISSUE TITLE
Local File Opton Can't Load Javascript

### ISSUE THREAD

**Issue by SalmaBegumJSR** [cadeyrn/newtaboverride#289]
Greetings,
i am trying to use javascript in local file html, when i load the local file directly it works fine, 

but when i load using extension, it shows me following error message:
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:15:9`

i tried both inline javascript and also using remote web js file, both render same error message,

after some research i even set following header/meta on head, but still not working

`<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">`

so? how can i load the javascript properly? please help me out..

thanks in advance..

**Comment by cadeyrn** [comment]
Hi,

if you want to use a local file without restrictions you have to setup a local server so that you can open the page via https:// or http://. It's very easy with a tool like XAMPP or MAMP. The local file option of New Tab Override only supports the most simple use cases.
