### ISSUE TITLE
focus on webpage 

### ISSUE THREAD

**Issue by WilLigtenberg** [cadeyrn/newtaboverride#29]
Hi<
I've just installed the New Tab Override extension but am not able to get focus on my webpage instead it stays on the adress bar

**Comment by cadeyrn** [comment]
Please show me a screenshot of the add-on settings with your configuration and tell me which version of Firefox and which operating system you are using.

**Comment by cadeyrn** [comment]
Please show me a screenshot of the add-on settings with your configuration and tell me which version of Firefox and which operating system you are using.

**Comment by WilLigtenberg** [comment]
Hi Sören,

 

thank you for your quick reponse.

I’m using Firefox 55.0.2 (32 bits), W7 (64 bits) and in attachment you will see the setting of the add-on

 

Kind regards,

 

Wil

**Comment by cadeyrn** [comment]
Unfortunately there is no attachment.

**Comment by WilLigtenberg** [comment]
Hi Sören,

 

Don’t get it because I attached the screendump. in attachment again but also below.

 

 



Kind regards,

 

Wil

**Comment by cadeyrn** [comment]
still no attachment…

**Comment by WilLigtenberg** [comment]
Hi Soren,

 

The attachment was also copied in the email

 

Thx,

 

Wil

**Comment by cadeyrn** [comment]
There is no e-mail, I only see your GitHub comments and these comments does not include any images…

**Comment by WilLigtenberg** [comment]
![screenhunter_039](https://user-images.githubusercontent.com/31316947/29712581-e3bd22f2-899a-11e7-977d-47ec4645a32e.jpg)

**Comment by WilLigtenberg** [comment]
Hi Soren,
Just attached the image.
Thx,

**Comment by WilLigtenberg** [comment]
Sorry I closed and re-opened the issue because I'm not familiar with GitHub
Thx @cadeyrn

**Comment by cadeyrn** [comment]
I tested and cannot reproduce. With your settings the focus is on the Google search field on my system (macOS 10.13 Beta, Firefox 55).

**Comment by cadeyrn** [comment]
Can you reproduce the issue with a fresh Firefox profile?

**Comment by cadeyrn** [comment]
closed due to inactivity. Can be reopened if there are new information.
