### ISSUE TITLE
Not working any more it used to!

### ISSUE THREAD

**Issue by jamieduk** [cadeyrn/newtaboverride#30]
Not working for some reason can you force it to work?

**Comment by cadeyrn** [comment]
I neither know your settings nor your Firefox version nor your operating system nor what "not working" means. I need more information…

**Comment by blizx** [comment]
How does the local file works? Before the update my new tab page looks like this:-
[i.imgur.com/8pzWGkN.jpg](url)

And now it looks like:-
[http://i.imgur.com/AN6ghBX.png](url)

**Comment by cadeyrn** [comment]
Please open your own ticket if you have questions.

There is a description on the settings page of New Tab Override. Please read the description. By the way, it's super ease to set up a local host, just use MAMP or XAMPP. Then you don't need the local file option and you can use the custom url option without any restriction.

**Comment by cadeyrn** [comment]
@jamieduk: waiting for more info.

**Comment by cadeyrn** [comment]
closed due to inactivity of issue opener. Can be reopened if there will be further input.
