### ISSUE TITLE
Move tabs below menu

### ISSUE THREAD

**Issue by PissedFirefoxUser** [cadeyrn/newtaboverride#301]
I love the NewTabOverride add-on. Please add a feature to let the user choose putting the tab bar above or below the menu. Firefox defaults to putting the tabs above the menu/address bar and I hate that! I want it below. Thank you!!

**Comment by cadeyrn** [comment]
This is neither possible for a WebExtension nor is this request related to New Tab Override at all. Please consult a Firefox support community if you need help for individual customizations via userChrome.css.

**Comment by PissedFirefoxUser** [comment]
Ok. Sorry.
