### ISSUE TITLE
The automatic emptying of the address bar or selecting the URL is currently not possible..

### ISSUE THREAD

**Issue by kaytrance** [cadeyrn/newtaboverride#304]
The issue is that, for example, [nightTab](https://addons.mozilla.org/en-US/firefox/addon/nighttab/) extension does the job flawlessly - it keeps it empty and focused. 

![nto](https://user-images.githubusercontent.com/6768891/210970585-be83ef96-ec16-48d5-9a82-a40b63578663.gif)

Maybe newtaboverride can check how do they are doing it?

**Comment by cadeyrn** [comment]
> Maybe newtaboverride can check how do they are doing it?

That extension uses a static page as new tab page. That's something totally different than a user-selected website as new tab page. It is not possible for WebExtensions to clear the address bar when opening a website.

**Comment by kaytrance** [comment]
With custom URL yes, but what about "local file" option? In that case it also uses a static page put into extension's folder. Does that count as static page?

**Comment by AmirSimantov** [comment]
Is it possible, at least, to SELECT the URL? What happens is that every time I open a tab and start to type, the homepage URL is appended to what I type...

**Comment by cadeyrn** [comment]
No, that's not possible.

**Comment by AmirSimantov** [comment]
Thanks. What's the alternative, then?

**Comment by cadeyrn** [comment]
The alternative is not to use a custom new tab page at all.
