### ISSUE TITLE
How to solve the white screen problem?

### ISSUE THREAD

**Issue by i110077** [cadeyrn/newtaboverride#312]
Every time I open a new tab, the white screen will flicker. I searched for many solutions on the Internet but can't solve it. Is there a way to solve it? This is the biggest problem affecting the entire plugin.

**Comment by cadeyrn** [comment]
Do you use a dark Firefox theme?

**Comment by vatsal999** [comment]
This solution works for me.
https://fedidat.com/640-dark-newtab-firefox/
