### ISSUE TITLE
New tab, URL is not selected.

### ISSUE THREAD

**Issue by jasonm23** [cadeyrn/newtaboverride#315]
https://github.com/cadeyrn/newtaboverride/blob/2b45f902bc14626a2e1ac44cc8e8beba52521096/src/js/core/newtab.js#L87-L95

When opening a new tab and focus is on address bar, the extension should behave in the same way as the regular new tab.

Selecting the text so that user input isn't suffixed by the current url when they hit enter would make the workflow smoother.

@cadeyrn do you agree? I will be happy to put in the code if you do not have time available.

**Comment by cadeyrn** [comment]
> I will be happy to put in the code if you do not have time available

How do you want to solve it? AFAIK this is not possible for WebExtensions.

**Comment by jasonm23** [comment]
I figured the omnibar API would be able to do it, but if it can't clear, I guess, Ctrl-k is our friend.

**Comment by cadeyrn** [comment]
Omnibar is a term from Google Chrome. Do you mean the omnibox API? But that's something completely different and does not help for this use case. I also don't know how exactly Ctrl + K can be "our friend" within the extension.

**Comment by jasonm23** [comment]
If you're on mac or linux C-k will clear from the cursor to the end of line.

Omnibox is what I meant, yes.

**Comment by MaxandreOgeret** [comment]
This is still not resolved.

**Comment by cadeyrn** [comment]
> This is still not resolved.

… because it is still not possible.

**Comment by erdnuesse** [comment]
then the option to have the cursor in the address bar is pretty much worthless for 90% of all people. Or at least add a comment next to the setting so users are aware it's not a bug, but the only way to implement it.
