### ISSUE TITLE
Focus from address bar to main screen not working in Firefox 115

### ISSUE THREAD

**Issue by Mel47** [cadeyrn/newtaboverride#319]
As the title says, changing the focus from address bar to main screen is no longer working after Firefox updated to version 115.0.2 (64-bit). I still have Firefox 114.0.2 (64-bit) on another device and it's working fine there. Both machines have the same Windows 10 Pro version 22H2. I am using DuckDuck Go, but same thing happens with Google search too.

**Comment by cadeyrn** [comment]
Tested in Firefox 122 and the Google website. I can not reproduce.
