### ISSUE TITLE
clear addressbar when new tab opens

### ISSUE THREAD

**Issue by camoril** [cadeyrn/newtaboverride#325]
by default firefox clear addressbar when opening a tab.. with the addon there is no way to enable this behavior so everytime you open a new tab the addressbar shows the URL..is there a way to disable this? so everytime you open a new tab you can start typing without the need to clear the URL

pretty please?

**Comment by cadeyrn** [comment]
This is not possible for WebExtensions.

**Comment by Nisthar** [comment]
@cadeyrn is it possible to keep the address bar in focus and select all the text when new tab opens? this would make it easier to just type after opening new tabs.

**Comment by cadeyrn** [comment]
unfortunately not. :(
