### ISSUE TITLE
Allow disabling new tab overriding.

### ISSUE THREAD

**Issue by pegasusearl** [cadeyrn/newtaboverride#326]
Currently using this extension with firefox sync is a nightmare.
![image](https://github.com/cadeyrn/newtaboverride/assets/23167087/6c0ec00e-d799-4c96-b9bc-a9d2448dd96f)
In the past, I can change new tab behavior to use different extension, it will work for awhile but eventually New Tab Override will takeover.
Now it doesn't even let me change it to other new tab extension.

While I used New Tab Override open my self hosted homepage when at home, I don't use it at work, where I log in with the same firefox account, and my extensions is synced between these devices.
It would be nice if New Tab Override had a settings to... disable the overriding.

I still use the "Open Tab Next to Current" feature in both devices though.

**Comment by cadeyrn** [comment]
I don't understand the request - if you don't want to override the new tab page, why do you use the add-on at all? That it's there to override the new tab page is even the name of the add-on. And if you don't want to use the same add-ons on different devices, then you shouldn't sync your add-ons. 🤔

**Comment by pegasusearl** [comment]
I use it at home. But not at work.

While I don't want to sync extensions related to new tab, I still want to sync the rest of my many-many extensions, it's nice to not having to install these extensions one by one.

There are settings that can [disable syncing enabled state](https://wiki.mozilla.org/Services/Sync/Addon_Sync#Can_I_have_different_enabled_states_on_different_machines.3F) using `about:config`, but it doesn't work.
There is also [this ugly workaround](https://superuser.com/questions/1356615/disable-firefox-synchronisation-for-a-single-addon) but I try to avoid it.

**Comment by cadeyrn** [comment]
You can either sync all your add-ons or none of them. If there is a workaround, you can try it. But there is nothing I can do as developer of this add-on.

Since overriding the new tab page is THE one thing that this add-on is for, an option to disable it doesn't make sense to implement.
