### ISSUE TITLE
`about:` sites as new tab

### ISSUE THREAD

**Issue by herzkoenig** [cadeyrn/newtaboverride#327]
I would like to have my new tab display me the new Firefox View, accessible via "about:firefoxview-next".

Can you add support for this, please?

Ideally via allowing about: sites in the custom url option, so that one could also choose about:firefoxview-next#opentabs for example.

Edit: Similar to #310 Unable to open extension urls, `moz-extenstion` protocol

**Comment by cadeyrn** [comment]
Due to security restrictions, it's not possible for WebExtensions to open about:pages.
