### ISSUE TITLE
Clicking "New Tab" after Mozilla reload reverts to "New Tab Setting"

### ISSUE THREAD

**Issue by sprozzy** [cadeyrn/newtaboverride#328]
Clicking "New Tab" after Mozilla reload reverts to "New Tab Setting" and not the "custom url" previously set. Each time Mozilla Firefox is loaded I have to reset my "Custom url" to http://presearch.com

**Comment by cadeyrn** [comment]
If an add-on does not remember your settings, it sounds like a broken Firefox profile or the usage of some kind of cleaner software. Please test if you have the same experience in a new Firefox profile:

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
