### ISSUE TITLE
enhancement: feedback error message if user tries to input an unsupported `protocol:// `

### ISSUE THREAD

**Issue by amithm7** [cadeyrn/newtaboverride#334]
From gh-311

> a feedback / error message if unsupported (by firefox) protocol:// is detected would make a for a better user experience, than just prepending https.

**Comment by amithm7** [comment]
@cadeyrn Great :+1: 

Scope for improvement in be07f5463060522023737a57754803885e696fd0:

```js
// general protocol check
const PROTOCOL_REGEX = /^(.*):\/\//i;
```

This would even match URI's like: `example.com/abc://saas`, `example.com/abc?a=://saas`...

The regex from gh-311 would be better for URI's:

```js
// match any "protocol://" URI
const PROTOCOL_REGEX = /^[^:]+:\/\//;
```

Which matches a `<string not containing ':'>://`

**Comment by cadeyrn** [comment]
Thanks. But it doesn't seem to make a different in practice. With both regexes, I get the same error message with the example inputs. And I am not even sure if these examples are valid URLs.

A hundred percent correct URL validation is extremely complex and very susceptible to edge cases that are not correctly taken into account. That is why this is intentionally only a very simple form of validation that does not actually check the input according to any RFCs, but only in a very rudimentary way.

**Comment by amithm7** [comment]
This `localhost:8080/:///saas` is a valid URL I believe, but would be matched as a protocol otherwise.

**Comment by cadeyrn** [comment]
Okay, I changed the regex. Thanks again!
