### ISSUE TITLE
Deactivate new tab ocerride for specifiy URLs

### ISSUE THREAD

**Issue by hirschferkel** [cadeyrn/newtaboverride#34]
Since the new version of Tab Override id doesn't work like expected for some Websites. We use some internal websites which will open pop ups usually but tab override will force them to open a new tab instead. This way these pop ups disconnect to their parent tab and do not work properly anymore.

Please add funtionallity to either choose a kind of blacklist for Tab override or add specific options for pop ups or tabs.

Best

**Comment by cadeyrn** [comment]
I don't undertand the request. New Tab Override overrides the new tab page. What should be blacklisted? Could you provide a test case? Thank you.

**Comment by hirschferkel** [comment]
Thought ist was TabOverride to cause troubles but it seems to be a major problem of FireFox 55!
So i guess there is no problem with TabOverride.

Best

**Comment by cadeyrn** [comment]
Okay, thank you. ;)
