### ISSUE TITLE
It doesn't change the very very first private tab

### ISSUE THREAD

**Issue by bywkgexmkiltxh** [cadeyrn/newtaboverride#344]
When I create a new private instance (Ctrl + Shift + P), the first tab is _about:privatebrowsing_. The tabs I create in this private window **after** this first tab follow New Tab Override. This happens with **each new** private window, not the new tabs I create in these windows.

The goal I'm trying to achieve is getting rid of dark purple background in each new private tab and this extension nearly gets this done, the only left is the very very first private tab. I hope there's a solution for this.

**Comment by cadeyrn** [comment]
New Tab Override changes the tab that appears when you open **a new tab**, it does **not change the home page**. This is not related to the private mode at all, for new regular windows it's exactly the same.

**Comment by bywkgexmkiltxh** [comment]
I forgot to mention that I set: Settings > Home > New Windows and Tabs > Homepage and new windows > Custom URLs... > moz-extension://a2c959a2-5d7a-4cd4-b301-7009c5b3137f/html/newtab.html

Starting a regular session opens New Tab Override for the first page, but this doesn't apply to private sessions.

Doing this also results in the first private tab labeling as about:privatebrowsing instead of "New Private Tab".

Doing the sleight above isn't supported, so I believe you can't examine this to not collide with Mozilla...

**Comment by cadeyrn** [comment]
> I forgot to mention that I set: Settings > Home > New Windows and Tabs > Homepage and new windows > Custom URLs... > moz-extension://a2c959a2-5d7a-4cd4-b301-7009c5b3137f/html/newtab.html

This setting is not used for the private mode start page. But that's behavior of Firefox, nothing I could change.
