### ISSUE TITLE
<Script> in html file

### ISSUE THREAD

**Issue by THINGTHING202** [cadeyrn/newtaboverride#348]
Any sort of script file does not run.
What I have done to test and prove this is that, whenever I run index.html on new tab, any code in <script> seemingly does not run. But when I put that same code from <script> into the terminal to run it, it does what it is intended. Is there a way around this?

**Comment by cadeyrn** [comment]
As explained in the add-on: For complex uses cases with local files, you have to use a local server. This is very easy with XAMPP or a similar tool. There is no way around this.
