### ISSUE TITLE
Internal url "not valid url"

### ISSUE THREAD

**Issue by nOrphf** [cadeyrn/newtaboverride#350]
Hi

I would like to set my "new tab" page to chrome://browser/content/places/places.xhtml so I can see my bookmarks.
But NTO tells me it's not a valid URL.

Is there a better way to show bookmarks, or can NTO allow this URL?

Regards Lars

**Comment by cadeyrn** [comment]
It is not possible for WebExtensions to load chrome:// URIs as new tab page.
