### ISSUE TITLE
request: option to not add protocol in front of url

### ISSUE THREAD

**Issue by GordonRamsay-689** [cadeyrn/newtaboverride#353]
I am trying to add about:firefoxview as my new tab page. Using the Home Page setting is not working for this, even if I am able to set this as my new window page. The issue is that https:// is prepended to the url. Would be real nice to be able to open Firefox View on new page, or add some optional character that negates prepending protocol.

**Comment by cadeyrn** [comment]
It's not possible to use about: URIs as new tab pages. You always need https://, http:// or file:// as a protocol. So it gives the best user experience, if https:// will be added if no protocol is given.
