### ISSUE TITLE
I don't manage to get Super Start for new tabs again

### ISSUE THREAD

**Issue by Uglix** [cadeyrn/newtaboverride#36]
Once again firefox was destroyed by an update. *sigh* (I know! They have their reasons...)

Some time ago I had to install newtaboverride to get Superstart back on new tabs. Now even this doesn't work. Or at least I don't manage to get it done.

I read this in the comments on newtaboverride: "In order to use Superstart extension, you can go to about:config, look for extensions.superstart.enable.searchengine.select and change the valor to true. This way, you can make work your about:superstart custom url despite the http://."

I set all superstart valors to "true". But as soon as I insert WHATEVER in the field in newtabboverride, firefox would not open ANY new tab. I tried "about:superstart" but even with "about:blank" the same thing happens.

So I get only new tabs that are completely empty or I get no new tab at all. :-((

PLEASE help me! I am a "many tab personality", leave them open all the time!

Greetings
Karin

I attached screenshots.
![firefox config](https://user-images.githubusercontent.com/31486432/29888220-781b21f0-8dc0-11e7-8c16-786a96b7d93e.jpg)

![neuer tab einstellungen](https://user-images.githubusercontent.com/31486432/29888239-88fc2b4a-8dc0-11e7-82c1-31f6b609a512.jpg)

**Comment by cadeyrn** [comment]
Please ask the developers of Super Start for support of the Super Start extension. There are not about: URIs for extensions in a WebExtensions world, they have to update their extension.
