### ISSUE TITLE
Select custom URL

### ISSUE THREAD

**Issue by Putzeimer** [cadeyrn/newtaboverride#37]
If a new tab starts with a custom URL and the focus is set on the address bar, the custom URL is not selected. If you then start typing, the new text is added left to the existing URL. That leads to results as example.comhttp://www.custom.url if you forget to delete the custom URL manually.
In older Versions, the custom URL was selected and therfore overwritten by pressing the first letter.
Could you re-add that feature please?

Btw: if about:home is selected, the cursor is always set to the webpage, regardless of the option "set to webpage instead of address bar".

**Comment by cadeyrn** [comment]
> If a new tab starts with a custom URL and the focus is set on the address bar, the custom URL is not selected. If you then start typing, the new text is added left to the existing URL.

Please read the descriptions within the add-on! There you can read that this is a current WebExtension restriction and we have to wait for Mozilla. Clearing the address bar won't be possible before Firefox 57.

> Btw: if about:home is selected, the cursor is always set to the webpage, regardless of the option "set to webpage instead of address bar".

The last time I checked it worked. I'll check again later today.

**Comment by cadeyrn** [comment]
Not reproducible, works for me.
