### ISSUE TITLE
Unable to set local html page as new tab page

### ISSUE THREAD

**Issue by armaandh** [cadeyrn/newtaboverride#38]
I am trying to use [Tilde](https://github.com/cadejscroggins/tilde) as a new tab page. I download the html page, and have it on my local hard drive. I use your extension to find the file, and set it. However every time I open a new tab, the page is blank...

**Comment by derjoshder** [comment]
I have a local file which loads, the images are not shown though, **probably due to relative urls**. So that does not work for me either, as I don't want to start a server every time I use my browser....

**Comment by cadeyrn** [comment]
@derjoshder: Relative URLs don't work as you can read in the description within the add-on. You don't have to start a server every time you use the browser. It's a matter of right configration that you only have to start it once.

@armaandh: I'll have a look tomorrow if I can reproduce the issue.

**Comment by cadeyrn** [comment]
I can reproduce the issue and it seems that the Inline JavaScript is not executed. So I fear there is nothing what I can do and you have to either upload the file to a remote web server or to setup a local web server. It's not difficult with MAMP or XAMPP.
