### ISSUE TITLE
Home Page redirect

### ISSUE THREAD

**Issue by danieljoses** [cadeyrn/newtaboverride#39]
Hi is it possible to have an option to have a new tab to redirect to our home page? this would resolve the problem i am having trying to use the desktop add-on as my new tab page (https://addons.mozilla.org/en-GB/firefox/addon/desktop/)

**Comment by cadeyrn** [comment]
Hi,

no, it's not possible and I don't know if it will be possible in the future.

**Comment by cadeyrn** [comment]
There will be a new home page option in the next update of New Tab Override. But you can't use the home page option to "cheat" - even with the new home page option only http:// and https:// URIs are allowed.
