### ISSUE TITLE
Creating new Tab an other tab open the URL

### ISSUE THREAD

**Issue by vale5566** [cadeyrn/newtaboverride#40]
When i open a new tab and change then to an another tab.
The tab which i selected load the target page. Just in the first seconds.

**Comment by cadeyrn** [comment]
I don't understand. Could you please explain with more details the exact steps to reproduce? Thank you.

**Comment by vale5566** [comment]
I think the video can explain it: https://youtu.be/7EuDuU4DaMM

**Comment by cadeyrn** [comment]
I still don't understand. Why do you have an open tab with the html/newtab.html URI in the address bar? How did you configured New Tab Override? Please show me your configuration.

**Comment by vale5566** [comment]
This is the problem when i create a new Tab and then switch within a half second to an another Tab. Then NOT the new created Tab go to my chosen page. The tab which i selected in the half second go to my chosen page. (im my case to google.de)


Here is my configuration:
![unbenannt](https://user-images.githubusercontent.com/7194238/30002335-0f6a0588-90a7-11e7-8934-43ec6a21014b.PNG)

Sry for my bad english.

**Comment by cadeyrn** [comment]
But in your video there is already an empty tab open with this html/newtab.html URI and that's not expected. Where does this come from? With your settings there should be no empty tab with this URI.

When opening a new tab there is this URI in the address bar for a very short time, unfortunately this cannot be prevented, at least not in Firefox 55 and Firefox 56, maybe in a later version of Firefox.

**Comment by vale5566** [comment]
Ok, when its cannot be prevented then it's not an issue.
I have installed version 55.0.3.
Before the Web Extension update there was no URI in the address bar so i thinked it was an issue.

In the Video i do the same thing what i want to describe only switched my tab a half second after creating a new tab and then my new created tab showing only this URI.
