### ISSUE TITLE
Cannot use chrome urls

### ISSUE THREAD

**Issue by juliodcs** [cadeyrn/newtaboverride#43]
Hi,

I'm trying to use chrome://browser/content/bookmarks/bookmarksPanel.xul as the URL.

However, once I load a new tab, it is replaced by

http://**chrome//**browser/content/bookmarks/bookmarksPanel.xul

Could this be supported?

Thank you,
Best regards

**Comment by cadeyrn** [comment]
Hi,

no, it's not possible for WebExtensions. Sorry.
