### ISSUE TITLE
New Tab Override is turned off.

### ISSUE THREAD

**Issue by jack34561** [cadeyrn/newtaboverride#47]
With Firefox 55.0.3, New Tab Override 8.0.0 and Windows 10 version 1703 (PC), I installed New Tab Override and it worked fine. If I close Firefox and restart it, New Tab Override does not work. If I disable and then enable New Tab Override, New Tab Override works. But the next time I start Firefox, New Tab Override does not work. What am I doing wrong? Thanks

**Comment by cadeyrn** [comment]
Something seems to be broken with your Firefox. Please test if you can reproduce the issue with a new Firefox profile:

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by jack34561** [comment]
A new profile solved my problem. Thank you!

**Comment by cadeyrn** [comment]
Great!
