### ISSUE TITLE
It's just not working

### ISSUE THREAD

**Issue by willow315** [cadeyrn/newtaboverride#49]
I have this listed in my extensions/add-ons, as the replacement for Custom New Tab. But suddenly, a Yahoo screen shows up and I have not configured that anywhere. The New Tab override is set to open https://www.wusf.usf.edu.  

So what's up with that? Where can it be configured properly?

**Comment by cadeyrn** [comment]
That sounds like adware/malware. You should check your system. New Tab Override only works on "clean" systems.

**Comment by willow315** [comment]
Willow Wright
Director of Digital Services
WUSF Public Media
wwright@wusf.org<mailto:wwright@wusf.org>
813-905-6908
www.wusf.org<http://www.wusf.org/>

[eMail_Sig_SnapJudgment_Aug17_96ppi_400w]<https://www.wusf.usf.edu/wusf_events/snap_judgment_2017?utm_source=signature-email&utm_medium=email&utm_campaign=SnapJudgement_Aug2017&utm_content=imagelink>

**Comment by cadeyrn** [comment]
I don't see any content in your last comment, only your mail signature…
