### ISSUE TITLE
[7.0.0] Not support localhost URL

### ISSUE THREAD

**Issue by Latreso** [cadeyrn/newtaboverride#5]
Custom URL option not support "localhost" (witch i really need) and IP adress (it's not necessary):

For example:
"localhost/my_page"
"http://localhost/my_page"
"127.0.0.1/my_page"
etc.

**Comment by cadeyrn** [comment]
It's fixed in current development version. "localhost/my_page" and "127.0.0.1/my_page" are still not working because the protocol is missing but I will implement another change to automatically assume "http://" when the protocol is missing.

**Comment by cadeyrn** [comment]
> "localhost/my_page" and "127.0.0.1/my_page" are still not working because the protocol is missing but I will implement another change to automatically assume "http://" when the protocol is missing.

Done. All of your examples are working now. I uploaded the update to addons.mozilla.org a few minutes ago.

**Comment by cadeyrn** [comment]
New Tab Override 7.1.0 is available on addons.mozilla.org now.
