### ISSUE TITLE
chrome:// links not working...

### ISSUE THREAD

**Issue by localhorst24** [cadeyrn/newtaboverride#56]
...instead default search will opended. (as own url)

chrome://fastdial/content/fastdial.html

**Comment by cadeyrn** [comment]
It's a) not possible for WebExtensions to use chrome:// URIs as new tab page and b) since it's also not possible for WebExtensions to have a chrome:// URI the Fast Dial add-on has to be updated, otherwise it won't be compatible with Firefox 57 and higher.
