### ISSUE TITLE
Add about:newtab

### ISSUE THREAD

**Issue by Volpad** [cadeyrn/newtaboverride#57]
Can you please add about:newtab on the options?

Thank you

**Comment by cadeyrn** [comment]
If you want to use about:newtab just disable the add-on, it's the default of Firefox.

**Comment by Volpad** [comment]
Not on private mode.

I want it on private mode.

On 20 September 2017 21:06:03 EEST, "Sören Hentzschel" <notifications@github.com> wrote:
>If you want to use about:newtab just disable the add-on, it's the
>default of Firefox.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cadeyrn/newtaboverride/issues/57#issuecomment-330933586

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cadeyrn** [comment]
You didn't say that. However, at the moment it's not possible for WebExtensions to set "about:newtab" as new tab page. Maybe in Firefox 58, but not in Firefox 55/56/57.

**Comment by Volpad** [comment]
Yes, sorry..

I discovered that, by tweaking the about:home case, in the newtab.js and
trying the modified xpi.

But i did that after i opened the issue ticket.

However, thank you very much for your answer.

Best Regards,

On Thu, Sep 21, 2017 at 12:00 AM, Sören Hentzschel <notifications@github.com

**Comment by cadeyrn** [comment]
You're welcome.

If / Once it will be possible in the future, a "about:newtab" option will be implemented in New Tab Override.
