### ISSUE TITLE
moz-extension://111bf922-c774-46e4-8eb4-19c577329f68/html/newtab.html

### ISSUE THREAD

**Issue by FreshhhHub** [cadeyrn/newtaboverride#58]
moz-extension://111bf922-c774-46e4-8eb4-19c577329f68/html/newtab.html

I'm seeing this in the search bar everytime I'm opening a new tab and it's slow down my surf experience...

**Comment by cadeyrn** [comment]
New Tab Override does not do anything with the search bar. If you mean the address bar, there is nothing what I can do. The add-on has to load the script to override the new tab page and the script has a URL which is visible for a very short moment. But it has no negative performance impact so I don't think it really slows down your surf experience. However, once there will be a better solution I will implement a better solution. But for the moment, there is no better solution for WebExtensions.

**Comment by hipunk** [comment]
Hi,

I noticed that newtab-bookmarks
https://addons.mozilla.org/en-US/firefox/addon/newtab-bookmarks/
https://github.com/tborychowski/newtab-bookmarks
is able to clear the url bar? Maybe just borrowing that code is all that's needed.

Greetz,

hipunk

**Comment by cadeyrn** [comment]
This is because it's not dynamic. It's not possible to set the new tab page to a website and clear the address bar. You can only clear the address bar if a internal page of the add-on is used as new tab page.
