### ISSUE TITLE
'resource://'-like adresses to open extensions pages.

### ISSUE THREAD

**Issue by JulyMorning** [cadeyrn/newtaboverride#6]
Always used it with other extensions, particularly with «Mind the Time» that logs user's time on web. The last one creates its own stat-page using this kind of address:

— resource://jid0-hynmqxa9zqgfjadreri4n2ahksi-at-jetpack/data/index.html

Tried to modify the regexp checking on my own, and now «New Tab Override» consider it valid, but opens its own options when new tab opened. Please, fix it somehow. Thanks.

**Comment by cadeyrn** [comment]
Thank you for your suggestion.

This is not allowed for WebExtensions. WebExtension can only access their own ressources.
