### ISSUE TITLE
"Set focus to the web page instead of the address bar" checkbox not working

### ISSUE THREAD

**Issue by tezz99** [cadeyrn/newtaboverride#63]
Unchecking the check box does not stop focus from moving to the web page. When a new tab is opened, I would like to keep focus on the address bar.

Using latest version of Firefox (v55).

**Comment by cadeyrn** [comment]
I cannot reproduce. Please tell me your full New Tab Override configuration.

**Comment by tezz99** [comment]
Hi. It turns out, my web page was auto focusing to a particular element.
My apologies for the inconvenience.

**Comment by cadeyrn** [comment]
No problem! :)
