### ISSUE TITLE
Request: Option to disable in private browsing

### ISSUE THREAD

**Issue by sbrl** [cadeyrn/newtaboverride#64]
I'd like to be able to disable this extension when I'm in a private window, if that's possible please :smiley_cat:

**Comment by cadeyrn** [comment]
Thank you for your suggestion. I will investigate if it's possible for New Tab Override 10.0 (next release will be 9.0).

**Comment by sbrl** [comment]
Thanks!

**Comment by cadeyrn** [comment]
Unfortunately it's not possible. It's possible to detect if a window is private but you can't say that the extension script should only be called in non private windows, so I wanted to change the new tab url to "about:privatebrowsing". But WebExtensions are not allowed to open about:privatebrowsing.

**Comment by sbrl** [comment]
Hrm, ok. So I guess it's something that mozilla would have to implement themselves in firefox. Thanks for checking into it though! :smiley_cat:

**Comment by sbrl** [comment]
Update for anyone here who's interested: Firefox 67 beta brings the ability to disable arbitrary extensions in private mode browsing.

This issue is now sorted!

@cadeyrn
