### ISSUE TITLE
Request: Select the url in address bar by default

### ISSUE THREAD

**Issue by yekit** [cadeyrn/newtaboverride#65]
Instead of just focusing on address bar, can we have an option to select the whole url in address bar?

Scenario: Open a new tab
Given that I had selected custom URL as option
And when I open a new tab
Then the url in the address bar will be selected
And when I type a new url, it will replace the current url in address bar

**Comment by cadeyrn** [comment]
There are already some tickets about this request. It's not possible at the moment. Once it will be possible I will implement this.
