### ISSUE TITLE
Why does the new version require access to browsing history?

### ISSUE THREAD

**Issue by v1tesse** [cadeyrn/newtaboverride#68]
New tab override just updated and it asked for an additional permission - to access browsing history.
Could you please explain why that is needed?

**Comment by cadeyrn** [comment]
It's explained in the add-on's description:

> **Permissions**
>
> New Tab Override needs the permissions to access your tabs and your history. Why does New Tab Override need access to your history? It's needed to prevent spammy "moz-extension://" entries in your browsing history every time you open a new tab. There is no way to prevent this without this permission.

And in the release notes of version 9.0:

> [ENHANCEMENT] New Tab Override does no longer create useless history entries! That's why New Tab Override needs the permission to access the browser history beginning with version 9.0.0
