### ISSUE TITLE
Allow option to open new tab with link and bookmark

### ISSUE THREAD

**Issue by PoconoDave** [cadeyrn/newtaboverride#69]
Please integrate an option to open a new tab with clicking a link and/or bookmark - without needing to right click & hover over the "Open in a New Tab".  Would be very helpful

**Comment by cadeyrn** [comment]
Honestly I do not understand the request. New Tab Override overrides the new tab page, it has nothing to do with bookmarks and wheter bookmarks should open in the same or in a new tab.

But beginning with Firefox 57 you can set browser.tabs.loadBookmarksInTabs to true in about:config to open bookmarks in tabs.

**Comment by PoconoDave** [comment]
Thanks for the suggestion to use about:config to change at least one of the settings.  Ultimately I am looking for TabMixPlus to work with Firefox 57+, Firefox suggested this extension as a possible replacement - but i see that this extension has a different mission.

**Comment by cadeyrn** [comment]
Yeah, Tab Mix Plus has a lot of features, my add-on is specialized on one task, the replacement of the new tab page. ;)
