### ISSUE TITLE
add better URL validation again

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/newtaboverride#7]
A big part of the URL validation was removed in https://github.com/cadeyrn/newtaboverride/commit/f859d01b0b9923cfb0ecdf86ccb4ff68aee23aad to provide a quick solution for localhost URLs. Maybe a better validation can be re-added in the future.

**Comment by Latreso** [comment]
**[sugestion]** or add "disable URL validation" option

//

I  used browser debugger and i find the "browser.storage.local.set({ url : 'about:blank' });".
I set the "http://localhost/helper" but now "clear address bar" not work 
(like in about:blank - i know it's not working on other custom URL too)

//

For now i used addon only with about:blank option, and i have bookmark to my localhost site near "New tab" button :/

I hope Mozilla fix this problem, and in next version you change the URL validation to accept localhost adress again :)

**Comment by cadeyrn** [comment]
With the change in https://github.com/cadeyrn/newtaboverride/commit/f859d01b0b9923cfb0ecdf86ccb4ff68aee23aad the validation is more or less completely disabled, it only checks the protocol now. I would like to re-add a validation again but with localhost support because user errors should be prevented. It's not the highest priority. You should try New Tab Override 7.1 once released on addons.mozilla.org (it's already submitted).

Unfortunately clearing the address bar cannot be implemented at the moment but it will be possible in a future update of Firefox.

**Comment by ScoreUnder** [comment]
Given that punycode domains and machines on the local network can cause strange-looking URLs, I doubt there's any sensible validation scheme you can use that doesn't prevent someone from using a valid URL.

**Comment by SicariusNoctis** [comment]
I can't use the bookmarks page anymore:

    chrome://browser/content/bookmarks/bookmarksPanel.xul

**Comment by cadeyrn** [comment]
> Given that punycode domains and machines on the local network can cause strange-looking URLs, I doubt there's any sensible validation scheme you can use that doesn't prevent someone from using a valid URL.

That's why there is a standard for URLs. ;)

> I can't use the bookmarks page anymore:
> chrome://browser/content/bookmarks/bookmarksPanel.xul

Because it's not allowed for WebExtension. There is nothing what I can do.

**Comment by artemut** [comment]
The same problem for me (my custom url is chrome://desktop/content/desktop.html). I started reading reviews on the https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/ and understood that many users used your extension for the same reason.

I guess, it would be better to display 'Such a URL is not supported by the current version of Firefox' instead of 'This is not a valid URL'. It will make clear for users that the problem is not with your add-on.

**Comment by helq** [comment]
The current URL validation scheme doesn't allow me to use `about:privatebrowsing` :S. It be awesome if you could change it so it allows urls that start with `about:`

PS: thanks for this very helpful addon :)

**Comment by SicariusNoctis** [comment]
Would it be possible to have an option to redirect to the browser's home page? The home page URL can be manually set by the user in Firefox's Settings.

**Comment by cadeyrn** [comment]
> The current URL validation scheme doesn't allow me to use about:privatebrowsing :S. It be awesome if you could change it so it allows urls that start with about:

WebExtensions are only allowed to open a very small subset of about:pages. I have to test if about:privatebrowsing is allowed, but probably not.

> Would it be possible to have an option to redirect to the browser's home page? The home page URL can be manually set by the user in Firefox's Settings.

That's currently not possible with WebExtension but will be possible in the future. I don't know when it will be possible, but not before Firefox 57, that's already clear.

**Comment by Chilledpeperami** [comment]
Is it possible for new tab ovveride to open the following URL.

`moz-extension://8b389ce2-4060-462f-ab7f-b4ba4a026456/bkviewer.html`

Currently it's adding http:// before that and is sending me to some wierd domain.

**Comment by cadeyrn** [comment]
No, it's not possible.
