### ISSUE TITLE
add link to bugzilla.mozilla.org about missing "Clear address bar" API

### ISSUE THREAD

**Issue by kkot** [cadeyrn/newtaboverride#72]
In preferences it is mentioned that "Clear address bar" requires changes from Mozilla. Maybe it would be good to provide link to bugzilla.mozilla.org so that users can vote and see in which version missing API will be provided.

**Comment by cadeyrn** [comment]
Mozilla implemented such a option for overrides via manifest, now there is no open ticket for add-ons which implements a dynamic new tab override like this add-on.

**Comment by cadeyrn** [comment]
Implemented in New Tab Override 11.0, to be released next week.

**Comment by cadeyrn** [comment]
New Tab Override 11.0 has been released.
