### ISSUE TITLE
When opening a new tab, automatically "select all" in the address bar

### ISSUE THREAD

**Issue by xuhdev** [cadeyrn/newtaboverride#73]
If a user opts to make the cursor stay in the address bar when opening a new tab, they probably want to modify the address. Automatically "selecting all" would be helpful.

**Comment by cadeyrn** [comment]
That's not possible for WebExtensions.

**Comment by kkot** [comment]
@cadeyrn In my option there should be issue open for that so everybody can see that it is reported but waiting for changes from Mozilla. I think it would limit number of times people report it.

**Comment by cadeyrn** [comment]
Mozilla knows the issue and there are currently no plans to improve the situation in the near term. Once there will be a ticket with an approved idea I will link this ticket.
