### ISSUE TITLE
Hangs on extention newtab.html lookup.

### ISSUE THREAD

**Issue by theelous3** [cadeyrn/newtaboverride#79]
Using custom url. Url is remote and responsive.

Add-on enabled, yadda yadda.

`moz-extension://6bf8457c-0a98-47dc-a3ea-a2a36627a3ee/html/newtab.html`

https://i.imgur.com/FlJ27L1.png

**Comment by cadeyrn** [comment]
Please show me your add-on's settings and tell me which Firefox version do you use.

**Comment by theelous3** [comment]
All the info your heart could desire: https://i.imgur.com/gQ6cPBR.png

**Comment by theelous3** [comment]
Update: randomly working. I did install the restricted package from ubuntu ppa in the mean time (h.264 codecs etc.)

I use the add-on across several machines and all were fine for the duration of the one machine having issues.

**Comment by cadeyrn** [comment]
So is there still an issue? I cannot reproduce with these settings.

**Comment by theelous3** [comment]
Just mark it as linux weirdness and we'll move on :D
