### ISSUE TITLE
Update wrong tab when a new tab is opened in the background

### ISSUE THREAD

**Issue by s25g5d4** [cadeyrn/newtaboverride#81]
I'm using [Gesturefy](https://addons.mozilla.org/firefox/addon/gesturefy/) and this addon on my Firefox Developer Edition 57.0b12 (64 bit). I encountered a problem that when I open a new tab in the background by gestures, my current active tab will be cleared. After doing some trial and error, I found the problem exists only when New Tab Override enabled. This is really annoying, and, more than that, I can't even get my page back by hitting the go back button (this is caused by `loadReplace` option in `browser.tabs.update()`). So I read your code, tried to find the problem, and saw you didn't specify tabId in the `browser.tabs.update()` call.

According to the [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/update), if no tabId provided, current active tab will be selected to update. This is generally fine, but, in my case, the tab the script running in, is not the one activated (selected) at the moment. I mean when another extension opens a new tab, with `active` [option](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) set to false, the active tab remains unchanged, and the new tab opened in the background is the target tab New Tab Override running in. Then, because in the code you didn't specify which tab to update with, it updates the original one, not the new tab in the background.

I have a fix for this problem, I will make a pull request and please review my commit, thanks.

**Comment by cadeyrn** [comment]
Hi,

thank you for opening the issue and for the pull request. It's an edge case but I am happy to take this improvement because I can't see any downsides and it seems to solve your use case. Your fix will be part of New Tab Override, to be released the next week.

**Comment by s25g5d4** [comment]
Thank you! Love this addon!

**Comment by cadeyrn** [comment]
New Tab Override 11.0 has been released, needs Firefox 57 or higher.
