### ISSUE TITLE
Multiple tabs in quick succesion leaves many blank

### ISSUE THREAD

**Issue by ScoreUnder** [cadeyrn/newtaboverride#87]
If multiple tabs are opened in quick succession, many of them will fail to redirect, even though the URL bar on that tab will point to this extension.

**Comment by s25g5d4** [comment]
I believe it is related to #81, and the fix will be shipped next version. I could reproduce this problem, and confirmed that it is fixed in latest trunk.

**Comment by cadeyrn** [comment]
Thank you for reporting, @ScoreUnder, and thank you for testing with the latest development version, @s25g5d4. I'll keep this ticket open until New Tab Override 11.0 is released. Please test with New Tab Override 11.0, @ScoreUnder, once released. It will be released this week, maybe today.

**Comment by cadeyrn** [comment]
New Tab Override 11.0 has been released, needs Firefox 57 or higher.

**Comment by ScoreUnder** [comment]
Looks fixed from here too. Thanks!

**Comment by cadeyrn** [comment]
Great, thanks yor checking!
