### ISSUE TITLE
Should not automatically add "http" scheme

### ISSUE THREAD

**Issue by urlgirl** [cadeyrn/newtaboverride#91]
The extension added the http scheme to the URI for another extension with the following result:

http://moz-extension://1493e228-1cc6-4e06-84c8-e49a61d4069b/data/speeddial/index.html

If possible, please omit the scheme if the URI already has one specified.

**Comment by cadeyrn** [comment]
It's not possible to use moz-extension URIs from other add-ons as new tab page.
