### ISSUE TITLE
Allow focusing blank page (about:blank)

### ISSUE THREAD

**Issue by embik** [cadeyrn/newtaboverride#92]
I noticed the `about:blank` option does not allow to shift focus to the page itself. I'm using Vimium-FF and use new tabs to open the vomnibar. Using `about:blank` as new tab page in Vimium-FF (Vimium allows opening a new tab when pressing `t`) shifts focus to the page itself and the vomnibar can be opened via `o`.

New Tab Override however focuses the address bar. Is it possible to introduce the same "focus website" option for `about:blank` as in other options?

**Comment by cadeyrn** [comment]
Hi,

I think it's possible. I didn't know that there is a use case for that. I will add this in the next feature update.

**Comment by embik** [comment]
Thank you, much appreciated! 😄

**Comment by devnoname120** [comment]
Actually these settings work perfectly with Vimium-FF. 👍 

![image](https://user-images.githubusercontent.com/2824100/33690882-defc6312-dae5-11e7-8c7a-88ca115f1434.png)

**Comment by cadeyrn** [comment]
Good point. New Tab Override uses "about:blank" as fallback if the custom url option is selected and no URL is entered. :)

**Comment by embik** [comment]
Thanks @devnoname120, you're absolutely right. Guess that makes my request kinda obsolete.

**Comment by cadeyrn** [comment]
I reopened the issue because there is a working workaround but it's still an workaround. The option to set the focus to the page should be offered for about:blank. ;)

**Comment by cadeyrn** [comment]
Fixed in development version of New Tab Override 12.0.

**Comment by cadeyrn** [comment]
New Tab Override 12.0 has been released a few moments ago.
