### ISSUE TITLE
Allow Opening Local "File///" In New Tab

### ISSUE THREAD

**Issue by Issimo52** [cadeyrn/newtaboverride#94]
Presently only http & https are allowed. I'd like to be able to open a very useful local htm file in a new tab.

**Comment by justamathnerd** [comment]
Currently, you can upload a local file to the extensions storage, but I haven't been able to use the functionality of my html file in this way. Hoping to see support for file/// added.

**Comment by cadeyrn** [comment]
That's not possible.
