### ISSUE TITLE
Using a local file

### ISSUE THREAD

**Issue by bobjbkln** [cadeyrn/newtaboverride#98]
Using the local file option, the background color of the HTML file does not show (i.e. it's white) on the new tab page.  Everything else shows correctly.  The background color does show correctly on the original homepage.

**Comment by cadeyrn** [comment]
I need to see your HTML file to say anything about it.

**Comment by bobjbkln** [comment]
Thank you for your attention.  Here is a zipped copy of the file which was originally created many years ago.  Key lines are 12 and 13.
[homeFX%20pageg.zip](https://github.com/cadeyrn/newtaboverride/files/1485700/homeFX.20pageg.zip)

**Comment by bobjbkln** [comment]
Bump

**Comment by bobjbkln** [comment]
Bump

**Comment by cadeyrn** [comment]
I will check that once I have time. I  I have a full-time job and I move to a new apartment this/next week.

**Comment by bobjbkln** [comment]
Understood.  Thank you.

**Comment by cadeyrn** [comment]
It's because of the Inline Styles. Inline Styles are not allowed by the Content Security Policy of WebExtensions.

Instead of:

`<body style="background-color: rgb(238, 247, 72);">`

you have to write

`<body>`

and to declare in the <head> of your document:

```
<style>
  body {
    rgb(238, 247, 72);
  }
</style>
```
