### ISSUE TITLE
Firefox webextension workaround - Roboform Start Page

### ISSUE THREAD

**Issue by KylieUser** [cadeyrn/newtaboverride#99]
I use New Tab Override to open my Roboform password manager Start Page with all my favorite logins. Unfortunately, it is no longer working on Firefox, because Roboform is a webextension. This is explained on the NTO options page. 

Here is my workaround:
1. Set up start.roboform.com as your home page. 
2. Leave it open for the entire browser session.
3. _Right_ click on a login icon and choose _Goto in New window._ 
4. Every time you want to login to a new site, go back to the first tab, your Roboform Start Page.

Of course, this should just be a temporary workaround. I hope Mozilla fixes this soon because I want to use NTO!

**Comment by dEb2LTLY** [comment]
This works:
https://addons.mozilla.org/en-US/firefox/addon/roboform/

**Comment by KylieUser** [comment]
The Roboform Firefox add on works in general, but the Start Page does not open consistently on a new tab. I have a ticket open with Roboform. They have been able to reproduce the problem and are working on a fix.

**Comment by cadeyrn** [comment]
I have to close this ticket because I use this issues tracker to keep track of open bugs and feature request. But thank you for posting your workaround.
